Repository ulaval/modul-components, pull requests merged in 2018-08, with the labels that each got.

#312 Feature/rich text editor
  conf/webpack.config.js
  lib/lib.ts
  package-lock.json
  package.json
  src/components/component-names.ts
  src/components/index.ts
  src/components/input-style/input-style.html
  src/components/input-style/input-style.scss
  src/components/input-style/input-style.ts
  src/components/rich-text-edit/__snapshots__/rich-text-edit.spec.ts.snap
  src/components/rich-text-edit/adapter/popup-plugin.ts
  src/components/rich-text-edit/adapter/vue-froala.html
  src/components/rich-text-edit/adapter/vue-froala.scss
  src/components/rich-text-edit/adapter/vue-froala.ts
  src/components/rich-text-edit/rich-text-edit-options.ts
  src/components/rich-text-edit/rich-text-edit.html
  src/components/rich-text-edit/rich-text-edit.scss
  src/components/rich-text-edit/rich-text-edit.spec.ts
  src/components/rich-text-edit/rich-text-edit.ts
  src/components/rich-text-edit/rich-text-license-plugin.ts
  src/components/rich-text/rich-text.html
  src/components/rich-text/rich-text.sandbox.html
  src/components/rich-text/rich-text.sandbox.ts
  src/components/rich-text/rich-text.scss
  src/components/rich-text/rich-text.ts
  src/components/validation-message/validation-message.html
  src/mixins/input-label/input-label.ts
  src/mixins/input-management/input-management.ts
  src/mixins/input-state/input-state.ts
  src/mixins/portal/portal.ts
  src/sandbox/index.ts
  src/styles/base/_base.scss
  src/utils/license/license.ts
  src/utils/modul/modul.ts
  src/utils/vue/vue.ts
  tests/app/main.ts
  tests/app/meta-init.ts
  tests/app/viewer.ts
Labels: help wanted, new component, question

#339 Appliquer automatiquement l'état « complété » lorsque l'indicateur de progression atteint 100%
  src/components/progress/__snapshots__/progress.spec.ts.snap
  src/components/progress/progress.html
  src/components/progress/progress.sandbox.html
  src/components/progress/progress.spec.ts
  src/components/progress/progress.ts
Labels: enhancement

#355 Add click and tap event in m-carousel
  src/components/carousel/carousel.html
  src/components/carousel/carousel.ts
Labels: enhancement

#361 Update the svg close name
  src/components/dialog/dialog.html
  src/components/dialog/dialog.sandbox.html
Labels: bug

#347 MODUL-298: New component m-menu
  src/components/accordion-group/__snapshots__/accordion-group.spec.ts.snap
  src/components/accordion/__snapshots__/accordion.spec.ts.snap
  src/components/accordion/accordion.sandbox.html
  src/components/component-names.ts
  src/components/error-message/__snapshots__/error-message.spec.ts.snap
  src/components/index.ts
  src/components/menu-item/menu-item-add.ts
  src/components/menu-item/menu-item-archive.ts
  src/components/menu-item/menu-item-delete.ts
  src/components/menu-item/menu-item-edit.ts
  src/components/menu-item/menu-item-predefined.html
  src/components/menu-item/menu-item.html
  src/components/menu-item/menu-item.scss
  src/components/menu-item/menu-item.ts
  src/components/menu/__snapshots__/menu.spec.ts.snap
  src/components/menu/menu-skins.scss
  src/components/menu/menu.html
  src/components/menu/menu.lang.en.json
  src/components/menu/menu.lang.fr.json
  src/components/menu/menu.sandbox.html
  src/components/menu/menu.sandbox.ts
  src/components/menu/menu.scss
  src/components/menu/menu.spec.ts
  src/components/menu/menu.ts
  src/components/option-item/option-item-add.ts
  src/components/option-item/option-item-archive.ts
  src/components/option-item/option-item-delete.ts
  src/components/option-item/option-item-edit.ts
  src/components/option-item/option-item-predefined.html
  src/components/option-item/option-item-predefined.ts
  src/components/option-item/option-item.html
  src/components/option-item/option-item.scss
  src/components/option-item/option-item.ts
  src/components/option/__snapshots__/option.spec.ts.snap
  src/components/option/option.html
  src/components/option/option.lang.en.json
  src/components/option/option.lang.fr.json
  src/components/option/option.sandbox.html
  src/components/option/option.sandbox.ts
  src/components/option/option.scss
  src/components/option/option.spec.ts
  src/components/option/option.ts
  src/components/plus/__snapshots__/plus.spec.ts.snap
  src/components/plus/plus.html
  src/components/plus/plus.scss
  src/components/plus/plus.ts
  src/lang/fr.ts
  src/sandbox/index.ts
  src/styles/abstracts/_var-layout.scss
  src/styles/base/_layout.scss
  tests/app/meta-init.ts
Labels: new component

#362 Remove useless click event
  src/components/carousel/carousel.html
  src/components/carousel/carousel.ts
Labels: enhancement

#368 MODUL-342 - itemEl.style in m-navbar-item is undefined
  src/components/navbar-item/navbar-item.ts
Labels: bug

#380 Amélioration de la navigation du carousel mobile
  src/components/carousel-item/carousel-item.html
  src/components/carousel-item/carousel-item.scss
  src/components/carousel-item/carousel-item.ts
  src/components/carousel/carousel.html
  src/components/carousel/carousel.sandbox.html
  src/components/carousel/carousel.sandbox.ts
  src/components/carousel/carousel.scss
  src/components/carousel/carousel.ts
Labels: enhancement

#370 MODUL-343 : Permettre au souligner du m-link d'apparaitre sur 2 lignes
  src/components/accordion-group/__snapshots__/accordion-group.spec.ts.snap
  src/components/error-message/__snapshots__/error-message.spec.ts.snap
  src/components/link/__snapshots__/link.spec.ts.snap
  src/components/link/link.html
  src/components/link/link.sandbox.html
  src/components/link/link.scss
  src/components/link/link.ts
  src/components/page-not-found/__snapshots__/page-not-found.spec.ts.snap
  src/components/session-expired/__snapshots__/session-expired.spec.ts.snap
  src/components/tooltip/__snapshots__/tooltip.spec.ts.snap
  src/components/tree-node/tree-node.scss
  src/components/tree-node/tree-node.spec.ts
Labels: bug

#410 Encapsulate a sortable so it won't accept items from another sortable
  src/directives/droppable/droppable.spec.ts
  src/directives/droppable/droppable.ts
  src/directives/sortable/sortable.spec.ts
  src/directives/sortable/sortable.ts
Labels: bug

#407 Bugfix/rte text selection and icons
  package.json
  src/components/rich-text-editor/adapter/vue-froala.scss
  src/components/rich-text-editor/adapter/vue-froala.spec.ts
  src/components/rich-text-editor/rich-text-editor-options.ts
  src/components/rich-text-editor/rich-text-editor.sandbox.html
  src/directives/domPlugin.ts
  src/directives/draggable/draggable.spec.ts
  src/directives/draggable/draggable.ts
  src/directives/droppable/droppable.spec.ts
  src/directives/droppable/droppable.ts
  src/utils/event/event.ts
  src/utils/modul/modul.ts
Labels: bug
