Repository ulaval/modul-components, pull requests merged in 2018-10, with the labels that each got.

#476 Feature/modul 445 rt einit on click
  package-lock.json
  package.json
  src/components/rich-text-editor/adapter/vue-froala.scss
  src/components/rich-text-editor/adapter/vue-froala.ts
  src/components/rich-text-editor/rich-text-editor-options.ts
  src/components/rich-text-editor/rich-text-editor.sandbox.html
  src/components/rich-text-editor/rich-text-editor.sandbox.ts
Labels: enhancement

#491 Tooltip on the icon button to close the dialog
  src/components/dialog/dialog.html
  src/components/dialog/dialog.lang.fr.json
  src/components/dialog/dialog.sandbox.html
  src/components/dialog/dialog.ts
  src/components/file-upload/__snapshots__/file-upload.spec.ts.snap
  src/components/icon-button/__snapshots__/icon-button.spec.ts.snap
  src/components/icon-button/icon-button.html
  src/components/icon-button/icon-button.ts
  src/components/list-item/__snapshots__/list-item.spec.ts.snap
  src/components/message/__snapshots__/message.spec.ts.snap
Labels: enhancement

#486 Lazy load portal
  src/components/datepicker/__snapshots__/datepicker.spec.ts.snap
  src/components/dialog/dialog.html
  src/components/dropdown/__snapshots__/dropdown.spec.ts.snap
  src/components/edit-window/edit-window.html
  src/components/edit-window/edit-window.ts
  src/components/modal/modal.html
  src/components/popper/popper.html
  src/components/popper/popper.ts
  src/components/sidebar/sidebar.html
  src/components/sidebar/sidebar.sandbox.html
  src/components/timepicker/__snapshots__/timepicker.spec.ts.snap
  src/mixins/portal/portal.ts
Labels: enhancement

#485 Feature/modul 244 add default tooltips to m icon file
  src/assets/icons/sprites-default.svg
  src/components/icon-file/__snapshots__/icon-file.spec.ts.snap
  src/components/icon-file/icon-file.lang.en.json
  src/components/icon-file/icon-file.lang.fr.json
  src/components/icon-file/icon-file.sandbox.html
  src/components/icon-file/icon-file.ts
  src/directives/badge/__snapshots__/badge.spec.ts.snap
  src/lang/fr.ts
Labels: enhancement

#480 Input management => Add a function to focus
  src/components/rich-text-editor/rich-text-editor.sandbox.html
  src/components/rich-text-editor/rich-text-editor.sandbox.ts
  src/mixins/input-management/input-management.ts
Labels: enhancement, question

#514 Feature/modul 495 rename m error template to m message page
  src/components/component-names.ts
  src/components/error-access-denied/error-access-denied.html
  src/components/error-access-denied/error-access-denied.sandbox.ts
  src/components/error-access-denied/error-access-denied.spec.ts
  src/components/error-access-denied/error-access-denied.ts
  src/components/error-browser-not-supported/error-browser-not-supported.html
  src/components/error-browser-not-supported/error-browser-not-supported.sandbox.ts
  src/components/error-browser-not-supported/error-browser-not-supported.spec.ts
  src/components/error-browser-not-supported/error-browser-not-supported.ts
  src/components/error-config-not-supported/error-config-not-supported.html
  src/components/error-config-not-supported/error-config-not-supported.sandbox.ts
  src/components/error-config-not-supported/error-config-not-supported.spec.ts
  src/components/error-config-not-supported/error-config-not-supported.ts
  src/components/error-cookies-not-supported/error-cookies-not-supported.html
  src/components/error-cookies-not-supported/error-cookies-not-supported.sandbox.ts
  src/components/error-cookies-not-supported/error-cookies-not-supported.spec.ts
  src/components/error-cookies-not-supported/error-cookies-not-supported.ts
  src/components/error-page-not-found/error-page-not-found.html
  src/components/error-page-not-found/error-page-not-found.sandbox.ts
  src/components/error-page-not-found/error-page-not-found.spec.ts
  src/components/error-page-not-found/error-page-not-found.ts
  src/components/error-technical-difficulty/error-technical-difficulty.html
  src/components/error-technical-difficulty/error-technical-difficulty.sandbox.ts
  src/components/error-technical-difficulty/error-technical-difficulty.spec.ts
  src/components/error-technical-difficulty/error-technical-difficulty.ts
  src/components/error-template/__snapshots__/error-template.spec.ts.snap
  src/components/index.ts
  src/components/message-page/__snapshots__/message-page.spec.ts.snap
  src/components/message-page/message-page.html
  src/components/message-page/message-page.sandbox.html
  src/components/message-page/message-page.sandbox.ts
  src/components/message-page/message-page.scss
  src/components/message-page/message-page.spec.ts
  src/components/message-page/message-page.ts
  src/components/message/message.html
  src/components/message/message.ts
  tests/app/meta-init.ts
Labels: enhancement

#513 Feature/modul 493 rename and define all modal windows
  src/components/component-names.ts
  src/components/dialog/dialog.html
  src/components/dialog/dialog.lang.en.json
  src/components/dialog/dialog.lang.fr.json
  src/components/dialog/dialog.sandbox.html
  src/components/dialog/dialog.scss
  src/components/dialog/dialog.ts
  src/components/edit-window/edit-window.sandbox.ts
  src/components/error-access-denied/error-access-denied.sandbox.html
  src/components/error-browser-not-supported/error-browser-not-supported.sandbox.html
  src/components/error-config-not-supported/error-config-not-supported.sandbox.html
  src/components/error-cookies-not-supported/error-cookies-not-supported.sandbox.html
  src/components/error-message/error-message.sandbox.html
  src/components/error-page-not-found/error-page-not-found.sandbox.html
  src/components/error-technical-difficulty/error-technical-difficulty.sandbox.html
  src/components/file-upload/__snapshots__/file-upload.spec.ts.snap
  src/components/file-upload/file-upload.html
  src/components/file-upload/file-upload.spec.ts
  src/components/file-upload/file-upload.ts
  src/components/index.ts
  src/components/inplace-edit/inplace-edit.html
  src/components/inplace-edit/inplace-edit.spec.ts
  src/components/inplace-edit/inplace-edit.ts
  src/components/modal/modal.html
  src/components/modal/modal.lang.en.json
  src/components/modal/modal.lang.fr.json
  src/components/modal/modal.sandbox.html
  src/components/modal/modal.scss
  src/components/modal/modal.ts
  src/components/overlay/overlay.html
  src/components/overlay/overlay.lang.en.json
  src/components/overlay/overlay.lang.fr.json
  src/components/overlay/overlay.sandbox.html
  src/components/overlay/overlay.sandbox.ts
  src/components/overlay/overlay.scss
  src/components/overlay/overlay.ts
  src/components/phone-number/phone-number.spec.ignore.ts
  src/components/popup/popup.sandbox.html
  src/components/rich-text-editor/rich-text-editor.sandbox.html
  src/components/sidebar/sidebar.html
  src/components/sidebar/sidebar.ts
  src/lang/fr.ts
  src/utils/dialog/alert.ts
  src/utils/dialog/confirm.ts
  src/utils/index.ts
  src/utils/vue/vue.ts
  tests/app/meta-init.ts
Labels: enhancement

#494 codeowners change
  .github/CODEOWNERS
Labels: enhancement

#478 Feature/modul 99 ajout entry point et typing a la distribution
  package.json
  src/components/components-plugin.ts
  src/components/index.ts
  src/directives/directives-plugin.ts
  src/directives/index.ts
  src/filters/filters-plugin.ts
  src/filters/index.ts
  src/index.ts
  src/lang/index.ts
  src/meta/index.ts
  src/mixins/index.ts
  src/services/index.ts
  src/utils/index.ts
  src/utils/utils-plugin.ts
Labels: enhancement

#499 MODUL-464 : Fix for dropdown undefined property HasFooterSlot
  src/components/dropdown/__snapshots__/dropdown.spec.ts.snap
  src/components/dropdown/dropdown.lang.fr.json
  src/components/dropdown/dropdown.spec.ts
  src/components/dropdown/dropdown.ts
Labels: bug

#507 MODUL-497 - Uniformiser les boutons du inplace-edit sur mobile
  src/components/inplace-edit/__snapshots__/inplace-edit.spec.ts.snap
  src/components/inplace-edit/inplace-edit.html
  src/components/inplace-edit/inplace-edit.scss
  src/components/inplace-edit/inplace-edit.spec.ts
Labels: enhancement

#523 MODUL-514 - Rendre asynchrone les slots du composant m-template
  src/components/template/template.html
  src/components/template/template.sandbox.html
  src/components/template/template.sandbox.ts
  src/components/template/template.scss
  src/components/template/template.ts
Labels: bug

#525 MODUL-519 - Changer libellés
  src/components/file-upload/file-upload.lang.en.json
  src/components/file-upload/file-upload.lang.fr.json
  src/components/file-upload/file-upload.spec.ts
Labels: bug

#532 MODUL-338 - overlay merge redone
  src/components/overlay/overlay.html
  src/components/overlay/overlay.ts
Labels: bug

#533 Fixed sandbox RTE not working
  src/components/rich-text-editor/rich-text-editor.sandbox.html
Labels: bug

#534 MODUL-490 - Transparent tap on modal
  src/components/modal/modal.scss
Labels: bug

#530 Changer le texte du bouton fermer de la modal
  src/components/modal/modal.lang.fr.json
Labels: enhancement

#508 Bugfix/modul 499 detection user agent file upload
  src/components/file-upload/__snapshots__/file-upload.spec.ts.snap
  src/components/file-upload/file-upload.html
  src/components/file-upload/file-upload.scss
  src/components/file-upload/file-upload.spec.ts
  src/components/file-upload/file-upload.ts
  src/utils/user-agent/user-agent.spec.ts
  src/utils/user-agent/user-agent.ts
Labels: enhancement

#497 Feature/modul 476 date time filters
  src/components/error-message/__snapshots__/error-message.spec.ts.snap
  src/components/error-message/error-message.html
  src/components/error-message/error-message.ts
  src/filters/date-time/date-time.lang.en.json
  src/filters/date-time/date-time.lang.fr.json
  src/filters/date-time/date-time.sandbox.html
  src/filters/date-time/date-time.sandbox.ts
  src/filters/date-time/date-time.spec.ts
  src/filters/date-time/date-time.ts
  src/filters/date/date.lang.en.json
  src/filters/date/date.lang.fr.json
  src/filters/date/date.sandbox.html
  src/filters/date/date.sandbox.ts
  src/filters/date/date.spec.ts
  src/filters/date/date.ts
  src/filters/filter-names.ts
  src/filters/filters-plugin.ts
  src/filters/time/time.lang.en.json
  src/filters/time/time.lang.fr.json
  src/filters/time/time.sandbox.html
  src/filters/time/time.sandbox.ts
  src/filters/time/time.spec.ts
  src/filters/time/time.ts
  src/lang/fr.ts
  src/utils/i18n/i18n.ts
  src/utils/str/str.ts
  tests/helpers/lang.ts
Labels: new feature

#539 MODUL-539: Il manque une bordure dans le navbar (skin:tab-light) lorsqu'il y a seulement un item
  src/components/navbar-item/navbar-item.scss
  src/components/navbar/navbar.sandbox.html
Labels: bug fix

#543 make rte work with input-style readonly property
  src/components/rich-text-editor/adapter/vue-froala.html
  src/components/rich-text-editor/adapter/vue-froala.scss
  src/components/rich-text-editor/adapter/vue-froala.ts
  src/components/rich-text-editor/rich-text-editor.html
  src/components/rich-text-editor/rich-text-editor.sandbox.html
  src/components/rich-text-editor/rich-text-editor.sandbox.ts
  src/components/textfield/textfield.sandbox.html
Labels: enhancement

#548 Feature/modul 505 m table 3
  src/components/component-names.ts
  src/components/components-plugin.ts
  src/components/table/__snapshots__/table.spec.ts.snap
  src/components/table/table.html
  src/components/table/table.lang.en.json
  src/components/table/table.lang.fr.json
  src/components/table/table.sandbox.html
  src/components/table/table.sandbox.scss
  src/components/table/table.sandbox.ts
  src/components/table/table.scss
  src/components/table/table.spec.ts
  src/components/table/table.ts
  src/lang/fr.ts
  tests/app/meta-init.ts
Labels: new feature

#549 MODUL-545: Ajouter l'icône not-allowed au textfield et l'icône chevron--right au datepicker
  src/assets/icons/sprites-default.svg
  src/components/datepicker/datepicker.html
  src/components/input-style/input-style.html
  tests/app/app-frame/app-frame.html
  tests/app/app-frame/app-frame.scss
  tests/app/attributes/attributes.html
  tests/app/index.html
  tests/app/media-queries/media-queries.html
  tests/app/navigation/navigation.html
  tests/app/viewer/viewer.html
Labels: bug fix

#541 MODUL-541: Ajustement du visuel de composant m-panel pour l'admission
  src/components/panel/panel.sandbox.html
  src/components/panel/panel.scss
Labels: enhancement

#546 Feature/modul 338_overlay_keyboard
  src/components/overlay/overlay.html
  src/components/overlay/overlay.scss
  src/components/overlay/overlay.ts
Labels: bug fix

#544 Directive scroll-to : faire défiler vers un élément spécifique dans la page
  src/components/scroll-top/scroll-top.sandbox.html
  src/directives/draggable/draggable.sandbox.ts
  src/directives/scroll-to/scroll-to-lib.ts
  src/directives/scroll-to/scroll-to.sandbox.html
  src/directives/scroll-to/scroll-to.sandbox.ts
  src/directives/scroll-to/scroll-to.ts
  src/utils/index.ts
  src/utils/scroll-to/scroll-to.ts
  src/utils/utils-plugin.ts
  src/utils/vue/vue.ts
  tests/app/main.ts
Labels: new feature
