Repository ulaval/modul-components, pull requests merged in 2018-04, with the labels that each got.

#177 Dropdown auto-selection on tab keydown
  src/components/datepicker/datepicker.html
  src/components/dropdown/dropdown.html
  src/components/dropdown/dropdown.ts
  src/components/timepicker/timepicker.html
  src/mixins/input-popup/input-popup.ts
  src/mixins/portal/portal.ts
Labels: enhancement

#175 Add open props to file-upload
  src/components/file-upload/file-upload.html
  src/components/file-upload/file-upload.ts
Labels: enhancement

#159 drag & drop components
  package-lock.json
  package.json
  src/directives/directive-names.ts
  src/directives/domPlugin.ts
  src/directives/draggable/draggable.ts
  src/directives/droppable/droppable.ts
  src/directives/index.ts
  src/directives/sortable/mouse.ts
  src/directives/sortable/sortable-group.ts
  src/directives/sortable/sortable.ts
  src/utils/polyfills.ts
  src/utils/vue/directive.ts
Labels: help wanted, new component, question

#200 Resolve blur effect
  src/components/icon-button/icon-button.scss
Labels: bug

#194 Feature/drag drop v2
  src/directives/directive-names.ts
  src/directives/domPlugin.ts
  src/directives/draggable/draggable-allow-scroll.ts
  src/directives/draggable/draggable.spec.ts
  src/directives/draggable/draggable.ts
  src/directives/droppable/droppable-group.spec.ts
  src/directives/droppable/droppable-group.ts
  src/directives/droppable/droppable.ts
  src/directives/index.ts
  src/directives/sortable/sortable-group.ts
  src/directives/sortable/sortable.ts
  src/directives/user-select/remove-user-select.spec.ts
  src/directives/user-select/remove-user-select.ts
  src/utils/mouse/mouse.ts
  src/utils/polyfills.ts
  src/utils/selection/selection.ts
  src/utils/vue/directive.ts
Labels: enhancement

#198 Feature/dropdown popper update
  src/components/dropdown/dropdown.ts
  src/components/popper/popper.ts
  src/components/popup/popup.html
  src/components/popup/popup.ts
Labels: bug
