Repository ulaval/modul-components, pull requests merged in 2018-12, with the labels that each got.

#598 Added special chars for translations
  src/utils/i18n/i18n.spec.lang.fr.json
  src/utils/i18n/i18n.spec.ts
  src/utils/i18n/i18n.ts
Labels: enhancement

#606 MODUL-601 - add fix to position right not working in switch component
  src/components/switch/switch.scss
Labels: bug fix

#577 Color and spacing functions
  .stylelintrc
  src/components/modal/modal.scss
  src/styles/abstracts/_cp-layout.scss
  src/styles/abstracts/_functions.scss
  src/styles/abstracts/_var-color.scss
  src/styles/abstracts/_var-layout.scss
  src/styles/abstracts/_variables.scss
  src/styles/base/_layout.scss
  src/styles/functions/_color.scss
  src/styles/functions/_functions.scss
  src/styles/functions/_map.scss
  src/styles/functions/_spacing.scss
  src/styles/main.css
Labels: enhancement

#607 Feature/modul-583 Changer le visuel des éléments de formulaires
  src/components/datepicker/__snapshots__/datepicker.spec.ts.snap
  src/components/input-style/input-style.html
  src/components/input-style/input-style.scss
  src/components/input-style/input-style.ts
  src/components/login/__snapshots__/login.spec.ts.snap
  src/components/rich-text-editor/adapter/vue-froala.scss
  src/components/textfield/textfield.html
  src/components/textfield/textfield.sandbox.html
  src/components/textfield/textfield.scss
  src/components/textfield/textfield.ts
  src/components/timepicker/__snapshots__/timepicker.spec.ts.snap
  src/styles/abstracts/_var-input-style.scss
Labels: enhancement

#616 Feature/modul-583_input-style (part II)
  src/components/datepicker/datepicker.html
  src/components/dropdown/dropdown.html
  src/components/icon-button/icon-button.scss
  src/components/inplace-edit/inplace-edit.sandbox.html
  src/components/input-style/input-style.html
  src/components/input-style/input-style.scss
  src/components/input-style/input-style.ts
  src/components/login/__snapshots__/login.spec.ts.snap
  src/components/rich-text-editor/adapter/vue-froala.scss
  src/components/rich-text-editor/rich-text-editor.html
  src/components/textarea/textarea.html
  src/components/textarea/textarea.sandbox.html
  src/components/textfield/__snapshots__/textfield.spec.ts.snap
  src/components/textfield/textfield.html
  src/components/textfield/textfield.lang.en.json
  src/components/textfield/textfield.lang.fr.json
  src/components/textfield/textfield.sandbox.html
  src/components/textfield/textfield.sandbox.ts
  src/components/textfield/textfield.scss
  src/components/textfield/textfield.ts
  src/components/timepicker/timepicker.html
  src/mixins/input-label/input-label.ts
  src/styles/abstracts/_var-input-style.scss
  src/styles/abstracts/_variables.scss
Labels: breaking change

#604 MODUL 597 - Modifier la gestion de l'arrêt du scroll dans la page (modul.ts)
  src/components/option/option.sandbox.html
  src/components/overlay/overlay.sandbox.html
  src/components/overlay/overlay.ts
  src/mixins/portal/portal.ts
  src/utils/modul/modul.ts
  tests/app/app-frame/app-frame.html
  tests/app/app-frame/app-frame.ts
Labels: bug fix

#612 Feature/modul 582 arbo multinode select
  package-lock.json
  src/components/checkbox/__snapshots__/checkbox.spec.ts.snap
  src/components/checkbox/checkbox.html
  src/components/checkbox/checkbox.sandbox.html
  src/components/checkbox/checkbox.scss
  src/components/checkbox/checkbox.spec.ts
  src/components/checkbox/checkbox.ts
  src/components/component-names.ts
  src/components/components-plugin.ts
  src/components/icon-file/icon-file.html
  src/components/icon/icon.html
  src/components/icon/icon.ts
  src/components/tree-icon/tree-icon.html
  src/components/tree-icon/tree-icon.scss
  src/components/tree-icon/tree-icon.spec.ts
  src/components/tree-icon/tree-icon.ts
  src/components/tree-node/__snapshots__/tree-node.spec.ts.snap
  src/components/tree-node/tree-node.html
  src/components/tree-node/tree-node.lang.en.json
  src/components/tree-node/tree-node.lang.fr.json
  src/components/tree-node/tree-node.ts
  src/components/tree/__snapshots__/tree.spec.ts.snap
  src/components/tree/component-names.ts
  src/components/tree/tree-icon/tree-icon.html
  src/components/tree/tree-icon/tree-icon.scss
  src/components/tree/tree-icon/tree-icon.spec.ts
  src/components/tree/tree-icon/tree-icon.ts
  src/components/tree/tree-node/__snapshots__/tree-node.spec.ts.snap
  src/components/tree/tree-node/tree-node.html
  src/components/tree/tree-node/tree-node.scss
  src/components/tree/tree-node/tree-node.spec.ts
  src/components/tree/tree-node/tree-node.ts
  src/components/tree/tree.html
  src/components/tree/tree.lang.en.json
  src/components/tree/tree.lang.fr.json
  src/components/tree/tree.sandbox.html
  src/components/tree/tree.sandbox.ts
  src/components/tree/tree.spec.ts
  src/components/tree/tree.ts
  src/lang/fr.ts
Labels: breaking change, enhancement

#625 Feature/modul-623_font-variable-fallback
  src/assets/fonts/SourceSansVariable-Italic.otf
  src/assets/fonts/SourceSansVariable-Italic.ttf
  src/assets/fonts/SourceSansVariable-Roman.otf
  src/assets/fonts/SourceSansVariable-Roman.ttf
  src/assets/fonts/source-sans-pro/SourceSansPro-Light.otf.woff
  src/assets/fonts/source-sans-pro/SourceSansPro-Light.otf.woff2
  src/assets/fonts/source-sans-pro/SourceSansPro-Light.ttf.woff
  src/assets/fonts/source-sans-pro/SourceSansPro-Light.ttf.woff2
  src/assets/fonts/source-sans-pro/SourceSansPro-Regular.otf.woff
  src/assets/fonts/source-sans-pro/SourceSansPro-Regular.otf.woff2
  src/assets/fonts/source-sans-pro/SourceSansPro-Regular.ttf.woff
  src/assets/fonts/source-sans-pro/SourceSansPro-Regular.ttf.woff2
  src/assets/fonts/source-sans-pro/SourceSansPro-Semibold.otf.woff
  src/assets/fonts/source-sans-pro/SourceSansPro-Semibold.otf.woff2
  src/assets/fonts/source-sans-pro/SourceSansPro-Semibold.ttf.woff
  src/assets/fonts/source-sans-pro/SourceSansPro-Semibold.ttf.woff2
  src/assets/fonts/source-sans-variable/SourceSansVariable-Italic.otf.woff
  src/assets/fonts/source-sans-variable/SourceSansVariable-Italic.otf.woff2
  src/assets/fonts/source-sans-variable/SourceSansVariable-Italic.ttf.woff
  src/assets/fonts/source-sans-variable/SourceSansVariable-Italic.ttf.woff2
  src/assets/fonts/source-sans-variable/SourceSansVariable-Roman.otf.woff
  src/assets/fonts/source-sans-variable/SourceSansVariable-Roman.otf.woff2
  src/assets/fonts/source-sans-variable/SourceSansVariable-Roman.ttf.woff
  src/assets/fonts/source-sans-variable/SourceSansVariable-Roman.ttf.woff2
  src/styles/abstracts/_mixins.scss
  src/styles/abstracts/_var-font.scss
  src/styles/abstracts/_variables.scss
  src/styles/base/_base.scss
  src/styles/base/_fonts.scss
  src/styles/base/_typography.scss
  src/styles/mixins/_mixins.scss
  src/styles/mixins/_typography.scss
  tests/app/typo-and-styles/typo-and-styles.html
Labels: breaking change, bug fix

#620 Feature/modul_612-613_input-style
  src/components/dropdown/dropdown.scss
  src/components/input-style/input-style.html
  src/components/input-style/input-style.scss
  src/components/input-style/input-style.ts
  src/styles/abstracts/_var-input-style.scss
Labels: bug fix, enhancement
