Repository ulaval/modul-components, pull requests merged in 2018-11, with the labels that each got.

#557 RTE fix Cannot read property 'edit' of undefined
  src/components/rich-text-editor/adapter/vue-froala.ts
Labels: bug fix

#552 Feature/modul 549 m table sandbox style
  src/components/table/table.sandbox.html
  src/components/table/table.sandbox.scss
Labels: bug fix

#554 fix problem in animation when scroll to bottom of the page
  src/directives/scroll-to/scroll-to.sandbox.html
  src/directives/scroll-to/scroll-to.sandbox.ts
  src/utils/scroll-to/scroll-to.ts
Labels: bug fix

#518 MODUL-508 - Tooltip - user text get highlighted on click. (firefox only)
  src/components/sidebar/sidebar.scss
  src/components/tooltip/tooltip.scss
Labels: bug fix

#547 Autoselect router-active tab when it exists on mounted
  src/components/navbar-item/navbar-item-helper.ts
  src/components/navbar-item/navbar-item.html
  src/components/navbar-item/navbar-item.spec.ts
  src/components/navbar-item/navbar-item.ts
  src/components/navbar/navbar.ts
Labels: enhancement, question

#553 Modul 159 remove peer dependencies
  package-lock.json
  package.json
  src/lang/index.ts
  src/utils/index.ts
  tests/app/main.ts
Labels: breaking change, enhancement

#560 fix settings and add html extension setting
  .htmlhintrc
  .vscode/extensions.json
  .vscode/settings.json
Labels: bug fix

#565 MODUL-552 - add basic styles to plain skin
  src/components/navbar-item/navbar-item.scss
  src/components/navbar/navbar.sandbox.html
  src/components/navbar/navbar.scss
Labels: enhancement

#556 Rework RTE model handling to make it more simple.
  src/components/rich-text-editor/adapter/vue-froala.html
  src/components/rich-text-editor/adapter/vue-froala.spec.ts
  src/components/rich-text-editor/adapter/vue-froala.ts
  src/components/rich-text-editor/rich-text-editor-options.ts
  src/components/rich-text-editor/rich-text-editor.sandbox.html
  src/components/rich-text-editor/rich-text-editor.sandbox.ts
Labels: bug fix

#555 Feature/modul_338_edit_window_keyboard
  src/components/modal/modal.html
  src/components/modal/modal.sandbox.html
  src/components/modal/modal.scss
  src/components/modal/modal.ts
  src/components/overlay/overlay.html
  src/components/overlay/overlay.sandbox.html
  src/components/overlay/overlay.scss
  src/components/overlay/overlay.ts
Labels: bug fix

#559 MODUL-538: Dans l'admission, le train disparaît lorsqu'on accède à la section directement par l'URL
  src/components/steppers-item/steppers-item.html
  src/components/steppers-item/steppers-item.scss
  src/components/steppers-item/steppers-item.ts
  src/components/steppers/steppers.html
  src/components/steppers/steppers.sandbox.html
  src/components/steppers/steppers.scss
  src/components/steppers/steppers.ts
Labels: bug fix

#562 MODUL-554 - Ajustement du comportement et de l'accessibilité des fenêtres (m-modal, m-dialog, m-popup, m-dropdown, etc.)
  src/components/dropdown/__snapshots__/dropdown.spec.ts.snap
  src/components/dropdown/dropdown.html
  src/components/option/__snapshots__/option.spec.ts.snap
  src/components/option/option.ts
  src/components/sidebar/sidebar.scss
  src/components/tooltip/tooltip.html
  src/utils/modul/modul.ts
Labels: bug fix

#550 Feature/modul 473 support poignees drag drop
  src/directives/draggable/draggable.sandbox.html
  src/directives/draggable/draggable.spec.ts
  src/directives/draggable/draggable.ts
Labels: enhancement

#545 Scope body et html css class
  src/components/dialog/dialog.html
  src/components/modal/modal.html
  src/components/overlay/overlay.html
  src/components/sidebar/sidebar.html
  src/styles/base/_base.scss
  src/styles/base/_layout.scss
  src/styles/base/_typography.scss
  src/styles/utils/_bullet-list.scss
  src/styles/utils/_button.scss
  src/styles/utils/_link.scss
  src/styles/utils/_table.scss
  src/styles/utils/_utils.scss
  src/styles/vendor/_normalize.scss
Labels: breaking change, enhancement

#564 fix scroll to inside a div
  src/directives/scroll-to/scroll-to.sandbox.html
  src/directives/scroll-to/scroll-to.sandbox.ts
  src/utils/scroll-to/scroll-to-service.sandbox.html
  src/utils/scroll-to/scroll-to-service.sandbox.ts
  src/utils/scroll-to/scroll-to.ts
  src/utils/utils-names.ts
  tests/app/attributes/attributes.html
  tests/app/attributes/attributes.ts
  tests/app/names-loader.ts
  tests/app/navigation/navigation.html
  tests/app/navigation/navigation.ts
  tests/app/router.ts
  tests/app/tsconfig.json
Labels: bug fix

#558 Modul 536 Add getting started to readme
  README.md
Labels: enhancement

#575 fix problem in edgeHTML 17 with modal
  src/mixins/portal/portal.ts
Labels: bug fix

#583 Add immediate watch on portal components
  src/mixins/portal/portal.ts
Labels: breaking change, bug fix

#601 P1 - Problème lors dans le positionnement du m-option
  src/utils/modul/modul.ts
Labels: bug fix

#600 m-table - changed scoped slot to add :key
  src/components/table/__snapshots__/table.spec.ts.snap
  src/components/table/table.html
  src/components/table/table.sandbox.html
  src/components/table/table.sandbox.ts
  src/components/table/table.spec.ts
Labels: breaking change
