Repository ulaval/modul-components, pull requests merged in 2019-02, with the labels that each got.

#690 MODUL-704 - improve RTE blur management
  src/components/rich-text-editor/adapter/vue-froala.ts
Labels: bug fix

#703 MODUL-627 - Cursor pointer on multiple-node-checkbox disabled
  src/components/checkbox/checkbox.scss
  src/components/tree/__snapshots__/tree.spec.ts.snap
  src/components/tree/tree-node/__snapshots__/tree-node.spec.ts.snap
  src/components/tree/tree-node/tree-node.html
  src/components/tree/tree.html
  src/components/tree/tree.scss
  src/styles/mixins/_button.scss
Labels: bug fix

#704 MODUL-711 - Added props preventOverflowEnable to popper
  src/components/dropdown/dropdown.sandbox.html
  src/components/popper/popper.ts
Labels: bug fix

#705 MODUL-723 - Added polyfill to allow Object.assign to be supported in …
  src/utils/polyfills.ts
Labels: enhancement

#695 [WIP] Tout ce qui est relatif au formulaire
  src/components/accordion/accordion-transition.ts
  src/components/accordion/accordion.html
  src/components/form/__snapshots__/form.spec.ts.snap
  src/components/form/form-field.spec.ts
  src/components/form/form-field.ts
  src/components/form/form.html
  src/components/form/form.sandbox.html
  src/components/form/form.sandbox.ts
  src/components/form/form.scss
  src/components/form/form.spec.ts
  src/components/form/form.ts
  src/directives/directive-names.ts
  src/directives/i18n/i18n.spec.ts
  src/utils/form/form-field-state/form-field-state.spec.ts
  src/utils/form/form-field-state/form-field-state.ts
  src/utils/form/form-field-validation/form-field-validation.spec.ts
  src/utils/form/form-field-validation/form-field-validation.ts
  src/utils/form/form-field/form-field.spec.ts
  src/utils/form/form-field/form-field.ts
  src/utils/form/form-state/form-state.spec.ts
  src/utils/form/form-state/form-state.ts
  src/utils/form/form-validation/form-validation.spec.ts
  src/utils/form/form-validation/form-validation.ts
  src/utils/form/form.spec.ts
  src/utils/form/form.ts
  src/utils/toast/toast-service.sandbox.html
  src/utils/toast/toast-service.sandbox.ts
  src/utils/toast/toast-service.ts
Labels: new feature

#710 MODUL-725 - Added property modifis.hide.enable=false in popper.js
  src/components/popper/popper.ts
Labels: bug fix

#713 MODUL-729 - formfield disparait si doit être focus
  src/components/form/form-field.ts
Labels: bug fix

#718 MODUL-735 - gerer les changes sur les types object pour form field
  src/utils/form/form-field/form-field.ts
Labels: bug fix

#723 MODUL-742 - gestion reponse serveur pour formulaire
  src/components/form/form.html
  src/components/form/form.sandbox.html
  src/components/form/form.sandbox.ts
  src/components/form/form.ts
Labels: enhancement

#721 Feature/modul 621 images rte
  src/assets/icons/svg/Froala-image-align-center.svg
  src/assets/icons/svg/Froala-image-align-left.svg
  src/assets/icons/svg/Froala-image-align-right.svg
  src/assets/icons/svg/Froala-replace.svg
  src/components/components-plugin.ts
  src/components/file-select/__snapshots__/file-select.spec.ts.snap
  src/components/file-select/file-select.html
  src/components/file-select/file-select.ts
  src/components/file-upload/__snapshots__/file-upload.spec.ts.snap
  src/components/file-upload/file-upload.html
  src/components/file-upload/file-upload.ts
  src/components/rich-text-editor/adapter/vue-froala.html
  src/components/rich-text-editor/adapter/vue-froala.scss
  src/components/rich-text-editor/adapter/vue-froala.spec.ts
  src/components/rich-text-editor/adapter/vue-froala.ts
  src/components/rich-text-editor/rich-text-editor-options.ts
  src/components/rich-text-editor/rich-text-editor.html
  src/components/rich-text-editor/rich-text-editor.lang.en.json
  src/components/rich-text-editor/rich-text-editor.lang.fr.json
  src/components/rich-text-editor/rich-text-editor.sandbox.html
  src/components/rich-text-editor/rich-text-editor.sandbox.ts
  src/components/rich-text-editor/rich-text-editor.ts
  src/utils/file/file.ts
Labels: enhancement

#720 MODUL-739 MTooltip Prop Size
  src/components/tooltip/tooltip.html
  src/components/tooltip/tooltip.sandbox.html
  src/components/tooltip/tooltip.scss
  src/components/tooltip/tooltip.ts
Labels: enhancement

#719 Feature/modul 722 change cursor not allowed
  src/styles/mixins/_button.scss
Labels: enhancement

#717 MODUL-734 - Add readonly mode to the m-tree
  src/components/tree/__snapshots__/tree.spec.ts.snap
  src/components/tree/tree-node/__snapshots__/tree-node.spec.ts.snap
  src/components/tree/tree-node/tree-node.html
  src/components/tree/tree-node/tree-node.scss
  src/components/tree/tree-node/tree-node.spec.ts
  src/components/tree/tree-node/tree-node.ts
  src/components/tree/tree.html
  src/components/tree/tree.sandbox.html
  src/components/tree/tree.spec.ts
  src/components/tree/tree.ts
Labels: enhancement

#716 MODUL-653 - toast animation
  src/components/toast/toast.scss
Labels: enhancement

#714 Feature/modul 638 input style
  src/components/datepicker/__snapshots__/datepicker.spec.ts.snap
  src/components/datepicker/datepicker.html
  src/components/input-style/__snapshots__/input-style.spec.ts.snap
  src/components/input-style/input-style.html
  src/components/input-style/input-style.scss
  src/components/input-style/input-style.spec.ts
  src/components/input-style/input-style.ts
  src/components/rich-text-editor/__snapshots__/rich-text-editor.spec.ts.snap
  src/components/textarea/__snapshots__/textarea.spec.ts.snap
  src/components/textfield/__snapshots__/textfield.spec.ts.snap
  src/components/timepicker/__snapshots__/timepicker.spec.ts.snap
Labels: bug fix

#692 Feature/modul 706 accordion
  src/components/accordion/__snapshots__/accordion.spec.ts.snap
  src/components/accordion/accordion.html
  src/components/accordion/accordion.sandbox.html
  src/components/accordion/accordion.scss
  src/components/accordion/accordion.ts
Labels: enhancement

#712 MODUL-726 - m-progress change colors of monochrome skin
  src/components/progress/progress.scss
Labels: enhancement

#728 fix some linter warning
  src/components/file-select/file-select.html
Labels: bug fix

#617 New input-group component
  package-lock.json
  src/components/component-names.ts
  src/components/components-plugin.ts
  src/components/input-group/__snapshots__/input-group.spec.ts.snap
  src/components/input-group/input-group.html
  src/components/input-group/input-group.sandbox.html
  src/components/input-group/input-group.sandbox.scss
  src/components/input-group/input-group.sandbox.ts
  src/components/input-group/input-group.scss
  src/components/input-group/input-group.spec.ts
  src/components/input-group/input-group.ts
Labels: new feature

#706 Add period-picker
  src/components/calendar/calendar-state/calendar-state-machine.spec.ts
  src/components/calendar/calendar-state/calendar-state-machine.ts
  src/components/calendar/calendar-state/state/abstract-calendar-state.ts
  src/components/calendar/calendar-state/state/calendar-range-date-state.spec.ts
  src/components/calendar/calendar-state/state/calendar-range-date-state.ts
  src/components/calendar/calendar-state/state/calendar-single-date-state.spec.ts
  src/components/calendar/calendar-state/state/calendar-single-date-state.ts
  src/components/calendar/calendar-state/state/calendar-state.ts
  src/components/component-names.ts
  src/components/datepicker/datepicker.html
  src/components/datepicker/datepicker.scss
  src/components/datepicker/datepicker.ts
  src/components/daterangepicker/__snapshots__/daterangepicker.spec.ts.snap
  src/components/daterangepicker/daterangepicker.html
  src/components/daterangepicker/daterangepicker.lang.en.json
  src/components/daterangepicker/daterangepicker.lang.fr.json
  src/components/daterangepicker/daterangepicker.sandbox.html
  src/components/daterangepicker/daterangepicker.sandbox.ts
  src/components/daterangepicker/daterangepicker.spec.ts
  src/components/daterangepicker/daterangepicker.ts
  src/components/periodpicker/__snapshots__/periodpicker.spec.ts.snap
  src/components/periodpicker/periodpicker.html
  src/components/periodpicker/periodpicker.sandbox.html
  src/components/periodpicker/periodpicker.sandbox.ts
  src/components/periodpicker/periodpicker.spec.ts
  src/components/periodpicker/periodpicker.ts
  src/lang/en.ts
  src/lang/fr.ts
Labels: new feature

#724 MODUL-708 - Fixed focus problems
  src/components/dropdown/dropdown.html
  src/components/dropdown/dropdown.ts
Labels: bug fix

#726 MODUL-432 - Added recursive function to find opened child and added t…
  src/components/tree/tree-node/__snapshots__/tree-node.spec.ts.snap
  src/components/tree/tree-node/tree-node.spec.ts
  src/components/tree/tree-node/tree-node.ts
  src/components/tree/tree.sandbox.ts
  src/components/tree/tree.spec.ts
Labels: enhancement

#739 MODUL-757 - vue-froala : bug fix
  src/components/rich-text-editor/adapter/vue-froala.ts
Labels: bug fix

#746 MODUL 763 - fix dropdown is focus
  package-lock.json
  src/components/dropdown/dropdown.html
  src/components/dropdown/dropdown.ts
Labels: bug fix

#762 Add daterangepicker to components-plugin
  src/components/components-plugin.ts
Labels: enhancement

#753 MODUL-748 - fixed popper limit in viewport
  src/components/datepicker/datepicker.sandbox.html
  src/components/option/option.sandbox.html
  src/components/popper/popper.sandbox.html
  src/components/popper/popper.ts
  src/components/tooltip/tooltip.sandbox.html
Labels: enhancement

#752 Bugfix/modul 768 fix compteur liste admin
  src/components/show-more/__snapshots__/show-more.spec.ts.snap
  src/components/show-more/show-more.html
  src/components/show-more/show-more.spec.ts
  src/components/show-more/show-more.ts
Labels: enhancement

#751 Feature/modul 627 m tree adjustment
  package-lock.json
  src/components/checkbox/checkbox.scss
  src/components/icon/icon.ts
  src/components/tree/__snapshots__/tree.spec.ts.snap
  src/components/tree/tree-icon/tree-icon.html
  src/components/tree/tree-icon/tree-icon.scss
  src/components/tree/tree-node/__snapshots__/tree-node.spec.ts.snap
  src/components/tree/tree-node/tree-node.html
  src/components/tree/tree-node/tree-node.scss
  src/components/tree/tree-node/tree-node.spec.ts
  src/components/tree/tree-node/tree-node.ts
  src/components/tree/tree.html
  src/components/tree/tree.sandbox.html
  src/components/tree/tree.scss
  src/components/tree/tree.ts
Labels: enhancement

#749 Feature/modul 705 rte problemes modal
  src/components/modal/modal.scss
  src/components/rich-text-editor/adapter/vue-froala.ts
  src/components/rich-text-editor/rich-text-editor.html
  src/components/rich-text-editor/rich-text-editor.sandbox.html
  src/components/rich-text-editor/rich-text-editor.sandbox.ts
  src/components/rich-text-editor/rich-text-editor.ts
Labels: bug fix

#744 MODUL-652 - Add dynamic properties in button sandbox
  src/components/button/button.sandbox.html
  src/components/button/button.sandbox.ts
  src/utils/enums/enums.ts
Labels: enhancement

#743 MODUL-664 - Add instant scroll to
  src/directives/scroll-to/scroll-to.sandbox.ts
  src/utils/scroll-to/scroll-to-service.sandbox.html
  src/utils/scroll-to/scroll-to-service.sandbox.ts
  src/utils/scroll-to/scroll-to.ts
Labels: enhancement

#733 MODUL-751 - Fixed the stuck in month selection when only one month wa…
  src/components/calendar/calendar-state/state/abstract-calendar-state.spec.base.ts
  src/components/calendar/calendar-state/state/abstract-calendar-state.ts
Labels: bug fix

#734 MODUL-755 - Added user assignation icon
  src/assets/icons/sprites-default.svg
Labels: enhancement

#742 Repair sortable tests
  src/directives/drag-and-drop/draggable/draggable.spec.ts
  src/directives/drag-and-drop/droppable/droppable.spec.ts
  src/directives/sortable/sortable.spec.ts
Labels: bug fix

#741 MODUL-760 - fix rich-text-editor padding issues
  src/components/rich-text-editor/adapter/vue-froala.scss
Labels: bug fix

#760 Feature/modul 663 m dropdown focus management
  src/components/dropdown/dropdown.html
  src/components/dropdown/dropdown.ts
  src/mixins/input-popup/input-popup.ts
Labels: bug fix, enhancement

#755 MODUL-770 - ability to display server error on form field
  src/components/form/form.sandbox.html
  src/components/form/form.sandbox.ts
  src/components/form/form.spec.ts
  src/utils/form/form-field/form-field.spec.ts
  src/utils/form/form-field/form-field.ts
  src/utils/form/form.spec.ts
Labels: breaking change, enhancement

#748 MODUL-764 - vue-froala : focus fix
  src/components/rich-text-editor/adapter/vue-froala.ts
  src/components/rich-text-editor/rich-text-editor.sandbox.html
  src/components/rich-text-editor/rich-text-editor.sandbox.ts
Labels: bug fix

#737 MODUL-758 - m-rich-text : added max-width for images
  src/components/rich-text/rich-text.sandbox.html
  src/components/rich-text/rich-text.scss
Labels: bug fix

#735 MODUL-756 - m-show-more : added skin prop
  src/components/show-more/show-more.html
  src/components/show-more/show-more.sandbox.html
  src/components/show-more/show-more.sandbox.ts
  src/components/show-more/show-more.ts
Labels: enhancement

#732 MODUL-752 - m-rich-text-editor kebab case for event names
  src/components/rich-text-editor/rich-text-editor.ts
Labels: bug fix

#759 Make periodpicker works with iso dates
  src/components/datepicker/datepicker.html
  src/components/datepicker/datepicker.ts
  src/components/daterangepicker/daterangepicker.html
  src/components/periodpicker/periodpicker.sandbox.html
  src/components/periodpicker/periodpicker.sandbox.ts
  src/components/periodpicker/periodpicker.spec.ts
  src/components/periodpicker/periodpicker.ts
  src/utils/modul-date/modul-date.spec.ts
  src/utils/modul-date/modul-date.ts
Labels: enhancement

#763 Feature/modul 776 period
  src/filters/date/date-time/date-time.spec.ts
  src/filters/date/date-time/date-time.ts
  src/filters/date/date.sandbox.html
  src/filters/date/date.sandbox.ts
  src/filters/date/date.ts
  src/filters/date/date/date.spec.ts
  src/filters/date/date/date.ts
  src/filters/date/period/period.lang.en.json
  src/filters/date/period/period.lang.fr.json
  src/filters/date/period/period.spec.ts
  src/filters/date/period/period.ts
  src/filters/filter-names.ts
  src/lang/en.ts
  src/lang/fr.ts
  src/utils/i18n/i18n.ts
Labels: new feature

#765 Add textfield interger type
  src/components/textfield/textfield.html
  src/components/textfield/textfield.sandbox.html
  src/components/textfield/textfield.spec.ts
  src/components/textfield/textfield.ts
Labels: enhancement

#773 Feature/modul 793 remove assignation icon
  src/assets/icons/sprites-default.svg
Labels: enhancement

#761 MODUL-745: Changer la nomenclature des classes dans le m-form
  src/components/form/form.html
  src/components/form/form.sandbox.html
  src/components/form/form.scss
Labels: enhancement
