Repository ulaval/modul-components, pull requests merged in 2019-05, with the labels that each got.

#933 Add the Error Page components (6) in storybook
  src/components/error-pages/error-access-denied/__snapshots__/error-access-denied.stories.ts.snap
  src/components/error-pages/error-access-denied/error-access-denied.sandbox.html
  src/components/error-pages/error-access-denied/error-access-denied.sandbox.ts
  src/components/error-pages/error-access-denied/error-access-denied.stories.ts
  src/components/error-pages/error-browser-not-supported/__snapshots__/error-browser-not-supported.stories.ts.snap
  src/components/error-pages/error-browser-not-supported/error-browser-not-supported.sandbox.html
  src/components/error-pages/error-browser-not-supported/error-browser-not-supported.sandbox.ts
  src/components/error-pages/error-browser-not-supported/error-browser-not-supported.stories.ts
  src/components/error-pages/error-config-not-supported/__snapshots__/error-config-not-supported.stories.ts.snap
  src/components/error-pages/error-config-not-supported/error-config-not-supported.sandbox.html
  src/components/error-pages/error-config-not-supported/error-config-not-supported.sandbox.ts
  src/components/error-pages/error-config-not-supported/error-config-not-supported.stories.ts
  src/components/error-pages/error-cookies-not-supported/__snapshots__/error-cookies-not-supported.stories.ts.snap
  src/components/error-pages/error-cookies-not-supported/error-cookies-not-supported.sandbox.html
  src/components/error-pages/error-cookies-not-supported/error-cookies-not-supported.sandbox.ts
  src/components/error-pages/error-cookies-not-supported/error-cookies-not-supported.stories.ts
  src/components/error-pages/error-page-not-found/__snapshots__/error-page-not-found.stories.ts.snap
  src/components/error-pages/error-page-not-found/error-page-not-found.sandbox.html
  src/components/error-pages/error-page-not-found/error-page-not-found.sandbox.ts
  src/components/error-pages/error-page-not-found/error-page-not-found.stories.ts
  src/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
  src/components/error-pages/error-technical-difficulty/error-technical-difficulty.sandbox.html
  src/components/error-pages/error-technical-difficulty/error-technical-difficulty.sandbox.ts
  src/components/error-pages/error-technical-difficulty/error-technical-difficulty.stories.ts
Labels: enhancement

#940 MODUL-965 - m-icon-button stories
  src/components/icon-button/__snapshots__/icon-button.stories.ts.snap
  src/components/icon-button/icon-button.sandbox.html
  src/components/icon-button/icon-button.sandbox.ts
  src/components/icon-button/icon-button.stories.ts
Labels: enhancement

#921 Add the m-textfield component to storybook
  src/components/textfield/__snapshots__/textfield.spec.ts.snap
  src/components/textfield/__snapshots__/textfield.stories.ts.snap
  src/components/textfield/textfield.sandbox.html
  src/components/textfield/textfield.sandbox.ts
  src/components/textfield/textfield.spec.ts
  src/components/textfield/textfield.stories.ts
Labels: enhancement

#911 MODUL-934 - Add recount for timeout in toaster when mouse leave
  src/components/toast/toast.spec.ts
  src/components/toast/toast.ts
Labels: bug fix

#926 MODUL-955: Le dernier item du navbar s'affiche mal
  src/components/navbar/navbar.sandbox.html
  src/components/navbar/navbar.scss
  src/components/navbar/navbar.ts
Labels: bug fix

#907 repeater base implementation
  src/components/component-names.ts
  src/components/repeater/__snapshots__/repeater.stories.ts.snap
  src/components/repeater/repeater.html
  src/components/repeater/repeater.lang.en.json
  src/components/repeater/repeater.lang.fr.json
  src/components/repeater/repeater.scss
  src/components/repeater/repeater.spec.ts
  src/components/repeater/repeater.stories.ts
  src/components/repeater/repeater.ts
  src/lang/en.ts
  src/lang/fr.ts
Labels: new feature

#905 MODUL-932: Améliorer l'interactivité du m-base-calendar
  src/components/calendar/calendar-renderer/base-calendar/__snapshots__/base-calendar.spec.ts.snap
  src/components/calendar/calendar-renderer/base-calendar/base-calendar.html
  src/components/calendar/calendar-renderer/base-calendar/base-calendar.scss
  src/components/calendar/calendar-renderer/base-calendar/base-calendar.ts
  src/components/calendar/calendar.ts
Labels: enhancement

#943 Erreur technique lors de la suppression d'un accordéon
  src/components/accordion-group/accordion-group.ts
Labels: bug fix

#932 MODUL-918: Nouveau composant m-chip
  src/assets/icons/sprites-default.svg
  src/components/chip/__snapshots__/chip.spec.ts.snap
  src/components/chip/__snapshots__/chip.stories.ts.snap
  src/components/chip/_chip-commons.scss
  src/components/chip/chip-add/__snapshots__/chip-add.spec.ts.snap
  src/components/chip/chip-add/__snapshots__/chip-add.stories.ts.snap
  src/components/chip/chip-add/chip-add.html
  src/components/chip/chip-add/chip-add.scss
  src/components/chip/chip-add/chip-add.spec.ts
  src/components/chip/chip-add/chip-add.stories.ts
  src/components/chip/chip-add/chip-add.ts
  src/components/chip/chip-delete/__snapshots__/chip-delete.spec.ts.snap
  src/components/chip/chip-delete/__snapshots__/chip-delete.stories.ts.snap
  src/components/chip/chip-delete/chip-delete.html
  src/components/chip/chip-delete/chip-delete.scss
  src/components/chip/chip-delete/chip-delete.spec.ts
  src/components/chip/chip-delete/chip-delete.stories.ts
  src/components/chip/chip-delete/chip-delete.ts
  src/components/chip/chip.html
  src/components/chip/chip.lang.en.json
  src/components/chip/chip.lang.fr.json
  src/components/chip/chip.spec.ts
  src/components/chip/chip.stories.ts
  src/components/chip/chip.ts
  src/components/component-names.ts
  src/components/components-plugin.ts
  src/lang/en.ts
  src/lang/fr.ts
Labels: new feature

#917 Feature/modul 874 visual modification search field
  src/components/icon-button/icon-button.scss
  src/components/input-style/input-style.scss
  src/components/textfield/textfield.html
Labels: breaking change UI

#914 Improve moneyfield precision display
  src/components/decimalfield/decimal.stories.ts
  src/components/decimalfield/decimalfield.ts
  src/components/input-mask/input-mask.ts
  src/components/moneyfield/__snapshots__/moneyfield.stories.ts.snap
  src/components/moneyfield/moneyfield.html
  src/components/moneyfield/moneyfield.stories.ts
Labels: enhancement

#946 MODUL-974 - Avoir l'option de mettre toujours le label dans le haut
  src/components/autocomplete/autocomplete.html
  src/components/autocomplete/autocomplete.sandbox.html
  src/components/autocomplete/autocomplete.ts
  src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
  src/components/datepicker/datepicker.html
  src/components/datepicker/datepicker.stories.ts
  src/components/decimalfield/__snapshots__/decimalfield.stories.ts.snap
  src/components/decimalfield/decimalfield.html
  src/components/decimalfield/decimalfield.stories.ts
  src/components/dropdown/__snapshots__/dropdown.stories.ts.snap
  src/components/dropdown/dropdown.html
  src/components/dropdown/dropdown.stories.ts
  src/components/input-style/input-style.ts
  src/components/integerfield/integerfield.html
  src/components/integerfield/integerfield.sandbox.html
  src/components/textarea/textarea.html
  src/components/textarea/textarea.sandbox.html
  src/components/textfield/__snapshots__/textfield.stories.ts.snap
  src/components/textfield/textfield.html
  src/components/textfield/textfield.stories.ts
  src/components/timepicker/__snapshots__/timepicker.stories.ts.snap
  src/components/timepicker/timepicker.html
  src/components/timepicker/timepicker.stories.ts
  src/mixins/input-management/input-management.ts
Labels: enhancement

#951 MODUL-975: Ajuster le visuel de l'entête des tableaux en mode sortable
  src/components/table/__snapshots__/table.spec.ts.snap
  src/components/table/__snapshots__/table.stories.ts.snap
  src/components/table/table.html
  src/components/table/table.scss
  src/components/table/table.ts
Labels: bug fix

#953 MODUL-966 - RTE close fix
  src/components/rich-text-editor/adapter/vue-froala.ts
Labels: bug fix

#954 MODUL-980 - Amélioration de l'entête du m-accordion-group
  src/components/accordion-group/__snapshots__/accordion-group.stories.ts.snap
  src/components/accordion-group/accordion-group.html
  src/components/accordion-group/accordion-group.scss
  src/components/accordion-group/accordion-group.stories.ts
  src/components/accordion-group/accordion-group.ts
Labels: breaking change, bug fix

#952 Feature/modul 976_repeater
  src/components/repeater/__snapshots__/repeater.stories.ts.snap
  src/components/repeater/repeater.html
  src/components/repeater/repeater.scss
  src/components/repeater/repeater.ts
Labels: enhancement

#959 Fix double emit input management prise #2
  src/components/integerfield/integerfield.sandbox.ts
  src/components/integerfield/integerfield.ts
  src/components/textfield/__snapshots__/textfield.stories.ts.snap
  src/components/textfield/textfield.stories.ts
  src/mixins/input-management/input-management.spec.ts
  src/mixins/input-management/input-management.ts
Labels: breaking change, bug fix

#957 MODUL-960 - m-datepicker - Gestion model saisie manuelle
  src/components/datepicker/datepicker.spec.ts
  src/components/datepicker/datepicker.ts
Labels: breaking change, bug fix

#949 Ajout d'un icon placeholder
  src/components/autocomplete/autocomplete.sandbox.html
  src/components/dropdown/__snapshots__/dropdown.spec.ts.snap
  src/components/dropdown/__snapshots__/dropdown.stories.ts.snap
  src/components/dropdown/dropdown.html
  src/components/dropdown/dropdown.scss
  src/components/dropdown/dropdown.stories.ts
  src/components/dropdown/dropdown.ts
  src/components/input-style/input-style.scss
  src/components/textfield/__snapshots__/textfield.stories.ts.snap
  src/components/textfield/textfield.stories.ts
  src/components/textfield/textfield.ts
  src/mixins/input-label/input-label.ts
  src/mixins/input-management/input-management.ts
Labels: enhancement

#961 MODUL-977 - fix misalignment between labeled and not labeled fields
  src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
  src/components/decimalfield/__snapshots__/decimalfield.stories.ts.snap
  src/components/input-style/__snapshots__/input-style.spec.ts.snap
  src/components/input-style/__snapshots__/input-style.stories.ts.snap
  src/components/input-style/input-style.html
  src/components/input-style/input-style.scss
  src/components/integerfield/__snapshots__/integerfield.spec.ts.snap
  src/components/moneyfield/__snapshots__/moneyfield.spec.ts.snap
  src/components/rich-text-editor/__snapshots__/rich-text-editor.spec.ts.snap
  src/components/textarea/__snapshots__/textarea.spec.ts.snap
  src/components/textfield/__snapshots__/textfield.stories.ts.snap
  src/components/textfield/textfield.stories.ts
  src/components/timepicker/__snapshots__/timepicker.stories.ts.snap
Labels: breaking change UI, bug fix

#955 Integrate the m-inplace-edit component into storybook
  src/components/inplace-edit/__snapshots__/inplace-edit.spec.ts.snap
  src/components/inplace-edit/__snapshots__/inplace-edit.stories.ts.snap
  src/components/inplace-edit/inplace-edit.sandbox.html
  src/components/inplace-edit/inplace-edit.sandbox.ts
  src/components/inplace-edit/inplace-edit.spec.ts
  src/components/inplace-edit/inplace-edit.stories.ts
Labels: enhancement

#962 Integrate the m-toast component into storybook
  src/components/toast/__snapshots__/toast.stories.ts.snap
  src/components/toast/toast.sandbox.html
  src/components/toast/toast.sandbox.ts
  src/components/toast/toast.stories.ts
Labels: enhancement

#956 Integrate the m-modal component into storybook
  src/components/modal/__snapshots__/modal.stories.ts.snap
  src/components/modal/modal.sandbox.html
  src/components/modal/modal.sandbox.ts
  src/components/modal/modal.stories.ts
Labels: enhancement

#964 Integrate m-spinner stories in storybook, delete sandboxes
  src/components/spinner/__snapshots__/spinner.spec.ts.snap
  src/components/spinner/__snapshots__/spinner.stories.ts.snap
  src/components/spinner/spinner.sandbox.html
  src/components/spinner/spinner.sandbox.ts
  src/components/spinner/spinner.spec.ts
  src/components/spinner/spinner.stories.ts
Labels: enhancement

#970 MODUL-996 - Correction affichage RTE
  src/components/dropdown/dropdown.scss
  src/components/icon/__snapshots__/icon.stories.ts.snap
  src/components/input-style/__snapshots__/input-style.stories.ts.snap
  src/components/input-style/input-style.scss
  src/components/input-style/input-style.stories.ts
Labels: bug fix

#971 MODUL-986 - fix label issues within searchfield
  src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
  src/components/decimalfield/__snapshots__/decimalfield.stories.ts.snap
  src/components/input-style/__snapshots__/input-style.spec.ts.snap
  src/components/input-style/__snapshots__/input-style.stories.ts.snap
  src/components/input-style/input-style.html
  src/components/input-style/input-style.scss
  src/components/integerfield/__snapshots__/integerfield.spec.ts.snap
  src/components/moneyfield/__snapshots__/moneyfield.spec.ts.snap
  src/components/rich-text-editor/__snapshots__/rich-text-editor.spec.ts.snap
  src/components/textarea/__snapshots__/textarea.spec.ts.snap
  src/components/textfield/__snapshots__/textfield.stories.ts.snap
  src/components/textfield/textfield.html
  src/components/timepicker/__snapshots__/timepicker.stories.ts.snap
Labels: bug fix

#983 MODUL-982 - added prop 'skipInputValidation' to skip input validation in datepicker
  src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
  src/components/datepicker/datepicker.stories.ts
  src/components/datepicker/datepicker.ts
Labels: enhancement

#982 MODUL-1020 - Ajout du mode waiting sur le m-overlay
  src/components/overlay/overlay.html
  src/components/overlay/overlay.sandbox.html
  src/components/overlay/overlay.sandbox.ts
  src/components/overlay/overlay.ts
Labels: enhancement

#981 MODUL-1019 : Supprimer le padding-bottom du m-accordion avec le skin="light"
  src/components/accordion/accordion.scss
Labels: breaking change UI

#979 MODUL-1013 - Enlever le placeholder icon sur Firefox et Edge
  src/components/dropdown/__snapshots__/dropdown.stories.ts.snap
  src/components/dropdown/dropdown.html
  src/components/dropdown/dropdown.scss
  src/components/dropdown/dropdown.ts
Labels: bug fix

#978 MODUL-1012 - add param to periodFormat to pass shortMonth true
  src/filters/date/date.sandbox.html
  src/filters/date/date.sandbox.ts
  src/filters/date/period/period.spec.ts
  src/filters/date/period/period.ts
Labels: enhancement

#975 MODUL-1006 - Ajout d'un espace insécable avant closing tag du m-limit-text
  src/components/limit-text/limit-text.sandbox.html
  src/components/limit-text/limit-text.ts
Labels: enhancement

#967 MODUL-994: Ajouter un état aux colonnes triables d'un tableau
  src/components/table/__snapshots__/table.spec.ts.snap
  src/components/table/__snapshots__/table.stories.ts.snap
  src/components/table/table.html
  src/components/table/table.lang.en.json
  src/components/table/table.lang.fr.json
  src/components/table/table.scss
  src/components/table/table.stories.ts
  src/components/table/table.ts
Labels: enhancement

#976 Integerfield now use cleavejs
  src/components/decimalfield/__snapshots__/decimalfield.stories.ts.snap
  src/components/decimalfield/decimalfield.html
  src/components/decimalfield/decimalfield.ts
  src/components/input-mask/input-mask.html
  src/components/input-mask/input-mask.ts
  src/components/integerfield/__snapshots__/integerfield.spec.ts.snap
  src/components/integerfield/integerfield.html
  src/components/integerfield/integerfield.sandbox.html
  src/components/integerfield/integerfield.ts
  src/components/moneyfield/__snapshots__/moneyfield.spec.ts.snap
Labels: breaking change

#968 CurrencyFormat: Add the possibility to hide decimal 0s
  src/components/moneyfield/__snapshots__/moneyfield.stories.ts.snap
  src/components/moneyfield/moneyfield.stories.ts
  src/filters/money/money.sandbox.ts
  src/filters/money/money.spec.ts
  src/filters/money/money.ts
Labels: enhancement

#990 Feature/modul 1037 convert form-all to stories
  src/components/form/__snapshots__/form.stories.ts.snap
  src/components/form/form.stories.ts
Labels: enhancement

#987 MODUL-1038 - Allow empty value for email min and max validator
  src/components/form/__snapshots__/form.stories.ts.snap
  src/components/form/form.stories.ts
  src/utils/form/validators/email/email.spec.ts
  src/utils/form/validators/email/email.ts
  src/utils/form/validators/max-length/max-length.spec.ts
  src/utils/form/validators/min-length/min-length.spec.ts
  src/utils/form/validators/min-length/min-length.ts
  src/utils/form/validators/required/required.spec.ts
Labels: breaking change, bug fix

#996 Add snapshot tests in storybook for the m-pagination component
  src/components/pagination/__snapshots__/pagination.spec.ts.snap
  src/components/pagination/__snapshots__/pagination.stories.ts.snap
  src/components/pagination/pagination.sandbox.html
  src/components/pagination/pagination.sandbox.ts
  src/components/pagination/pagination.spec.ts
  src/components/pagination/pagination.stories.ts
Labels: enhancement, work in progress

#994 MODUL-1054 - Add ID to formGroup
  src/components/form/__snapshots__/form.stories.ts.snap
  src/components/form/form.html
  src/components/form/form.stories.ts
  src/sandboxes/form/form-all.sandbox.html
  src/sandboxes/form/form-all.sandbox.ts
  src/sandboxes/form/form-complex.sandbox.html
Labels: enhancement

#993 MODUL-1052: Traduire les messages d'erreur du composant m-form
  src/components/form/__snapshots__/form.stories.ts.snap
  src/components/form/form.html
  src/components/form/form.lang.en.json
  src/components/form/form.lang.fr.json
  src/components/form/form.scss
  src/components/validation-message/validation-message.scss
Labels: enhancement

#972 Feature/modul 957 m dialog prop state
  src/components/dialog/__snapshots__/dialog.stories.ts.snap
  src/components/dialog/dialog.html
  src/components/dialog/dialog.scss
  src/components/dialog/dialog.stories.ts
  src/components/dialog/dialog.ts
  src/utils/dialog/dialog-service.sandbox.html
  src/utils/dialog/dialog-service.ts
Labels: breaking change

#988 MODUL-1006 - Ajuster l'espace du bouton de fermeture du limit-text
  src/components/limit-text/limit-text.ts
  src/components/textfield/__snapshots__/textfield.stories.ts.snap
  src/components/textfield/textfield.stories.ts
Labels: bug fix

#989 MODUL-1041: Retirer le corps de l'accordéon lorsque la $slots.dedault est vide
  src/components/accordion-group/__snapshots__/accordion-group.stories.ts.snap
  src/components/accordion-group/accordion-group.spec.ts
  src/components/accordion/__snapshots__/accordion.stories.ts.snap
  src/components/accordion/accordion.html
  src/components/accordion/accordion.scss
  src/components/accordion/accordion.spec.ts
  src/components/accordion/accordion.stories.ts
  src/components/accordion/accordion.ts
Labels: breaking change UI

#991 MODUL-1047 - Ajout des icônes m-svg__remove-circle et m-svg__remove-circle-filled
  src/assets/icons/sprites-default.svg
Labels: enhancement

#999 MODUL-1064: Ajouter des options au filtre de date
  src/filters/date/date.sandbox.html
  src/filters/date/date/date.ts
Labels: enhancement

#1003 MODUL-1068 - Add reactivity to initial value
  src/components/form/__snapshots__/form.stories.ts.snap
  src/components/form/form.stories.ts
  src/utils/form/form-control.ts
  src/utils/form/validators/max/max.spec.ts
  src/utils/form/validators/min/min.spec.ts
Labels: enhancement

#1004 Fix date format validator
  src/components/form/form.stories.ts
  src/utils/form/validators/date-format/date-format.spec.ts
  src/utils/form/validators/date-format/date-format.ts
Labels: bug fix
