Repository ulaval/modul-components, pull requests merged in 2019-07, with the labels that each got.

#1049 MODUL-1114 - the searchfield placeholder color is too light
  src/components/searchfield/__snapshots__/searchfield.stories.ts.snap
  src/components/searchfield/searchfield.scss
  src/components/searchfield/searchfield.stories.ts
Labels: bug fix

#1039 copy-to-clipboard
  package-lock.json
  package.json
  src/components/button/button.html
  src/components/button/button.ts
  src/components/component-names.ts
  src/components/copy-to-clipboard/__snapshots__/copy-to-clipboard.stories.ts.snap
  src/components/copy-to-clipboard/copy-to-clipboard-feedback.ts
  src/components/copy-to-clipboard/copy-to-clipboard.html
  src/components/copy-to-clipboard/copy-to-clipboard.lang.en.json
  src/components/copy-to-clipboard/copy-to-clipboard.lang.fr.json
  src/components/copy-to-clipboard/copy-to-clipboard.scss
  src/components/copy-to-clipboard/copy-to-clipboard.stories.ts
  src/components/copy-to-clipboard/copy-to-clipboard.ts
  src/components/input-style/input-style.scss
  src/components/login/__snapshots__/login.spec.ts.snap
  src/components/textfield/textfield.html
  src/components/textfield/textfield.ts
  src/components/toast/toast.ts
  src/lang/en.ts
  src/lang/fr.ts
  src/utils/input/input.ts
Labels: new feature

#1051 MODUL-1115 - Garder le contenu de l’accordéon dans le DOM
  src/components/accordion/__snapshots__/accordion.stories.ts.snap
  src/components/accordion/accordion.html
  src/components/accordion/accordion.stories.ts
  src/components/accordion/accordion.ts
Labels: enhancement

#1056 MODUL-1117 - Régression dans le phonefield
  src/components/phonefield/__snapshots__/phonefield.stories.ts.snap
  src/components/phonefield/phonefield.scss
  src/components/select/__snapshots__/select.stories.ts.snap
  src/components/select/select.html
Labels: bug fix

#986 Feature/modul 1016 address lookup
  src/components/address/address-autocomplete-field/__snapshots__/address-autocomplete-field.stories.ts.snap
  src/components/address/address-autocomplete-field/address-autocomplete-field.html
  src/components/address/address-autocomplete-field/address-autocomplete-field.stories.ts
  src/components/address/address-autocomplete-field/address-autocomplete-field.ts
  src/components/address/address-editor/__snapshots__/address-editor.stories.ts.snap
  src/components/address/address-editor/address-editor.html
  src/components/address/address-editor/address-editor.lang.en.json
  src/components/address/address-editor/address-editor.lang.fr.json
  src/components/address/address-editor/address-editor.stories.ts
  src/components/address/address-editor/address-editor.ts
  src/components/address/address-lookup-field/__snapshots__/address-lookup-field.stories.ts.snap
  src/components/address/address-lookup-field/address-lookup-field.html
  src/components/address/address-lookup-field/address-lookup-field.lang.en.json
  src/components/address/address-lookup-field/address-lookup-field.lang.fr.json
  src/components/address/address-lookup-field/address-lookup-field.scss
  src/components/address/address-lookup-field/address-lookup-field.stories.ts
  src/components/address/address-lookup-field/address-lookup-field.ts
  src/components/address/address-reader/__snapshots__/address-reader.stories.ts.snap
  src/components/address/address-reader/address-reader.html
  src/components/address/address-reader/address-reader.stories.ts
  src/components/address/address-reader/address-reader.ts
  src/components/address/address.ts
  src/components/autocomplete/autocomplete.html
  src/components/autocomplete/autocomplete.ts
  src/components/component-names.ts
  src/components/components-plugin.ts
  src/components/dropdown/dropdown.ts
  src/components/form/__snapshots__/form.stories.ts.snap
  src/lang/en.ts
  src/lang/fr.ts
  src/lib.ts
  src/utils/address-lookup/address-lookup-loqate-service.spec.ts
  src/utils/address-lookup/address-lookup-loqate-service.ts
  src/utils/address-lookup/address-lookup-service.sandbox.html
  src/utils/address-lookup/address-lookup-service.sandbox.ts
  src/utils/address-lookup/address-lookup-service.ts
  src/utils/address-lookup/address-lookup.plugin.ts
  src/utils/address-lookup/address.ts
Labels: new feature

#1058 Feature/modul 821 m limit elements
  src/components/component-names.ts
  src/components/limit-elements/__snapshots__/limit-elements.stories.ts.snap
  src/components/limit-elements/limit-elements.html
  src/components/limit-elements/limit-elements.lang.en.json
  src/components/limit-elements/limit-elements.lang.fr.json
  src/components/limit-elements/limit-elements.scss
  src/components/limit-elements/limit-elements.spec.ts
  src/components/limit-elements/limit-elements.stories.ts
  src/components/limit-elements/limit-elements.ts
  src/lang/en.ts
  src/lang/fr.ts
Labels: new feature

#1064 Make copy-to-clipboard use all it's container width by default
  src/components/copy-to-clipboard/__snapshots__/copy-to-clipboard.stories.ts.snap
  src/components/copy-to-clipboard/copy-to-clipboard.html
  src/components/copy-to-clipboard/copy-to-clipboard.stories.ts
  src/components/copy-to-clipboard/copy-to-clipboard.ts
Labels: bug fix

#1054 MODUL-1121: Refactor du composant m-accordeon-transition
  src/components/accordion-group/__snapshots__/accordion-group.stories.ts.snap
  src/components/accordion/__snapshots__/accordion.stories.ts.snap
  src/components/accordion/accordion-transition.scss
  src/components/accordion/accordion-transition.ts
  src/components/accordion/accordion.html
  src/components/accordion/accordion.scss
  src/components/accordion/accordion.ts
  src/components/character-count/__snapshots__/character-count.spec.ts.snap
  src/components/character-count/character-count.scss
  src/components/character-count/character-count.ts
  src/components/components-plugin.ts
  src/components/error-message/__snapshots__/error-message.spec.ts.snap
  src/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
  src/components/form/form.scss
  src/components/inplace-edit/inplace-edit.scss
  src/components/inplace-edit/inplace-edit.ts
  src/components/menu/menu-item/menu-item.scss
  src/components/menu/menu.scss
  src/components/menu/menu.ts
  src/components/message/message.scss
  src/components/navbar/navbar.sandbox.scss
  src/components/navbar/navbar.sandbox.ts
  src/components/transitions/accordion-transition/accordion-transition.html
  src/components/transitions/accordion-transition/accordion-transition.scss
  src/components/transitions/accordion-transition/accordion-transition.ts
  src/components/transitions/slide-transition/slide-transition.html
  src/components/transitions/slide-transition/slide-transition.sandbox.html
  src/components/transitions/slide-transition/slide-transition.sandbox.ts
  src/components/transitions/slide-transition/slide-transition.scss
  src/components/transitions/slide-transition/slide-transition.ts
  src/components/tree/tree-node/tree-node.scss
  src/components/tree/tree.ts
  src/components/validation-message/__snapshots__/validation-message.spec.ts.snap
  src/components/validation-message/validation-message.scss
  src/components/validation-message/validation-message.ts
Labels: breaking change, enhancement

#1057 MODUL-1106: Modifier l'affichage de la vue mois du datepicker
  src/components/accordion-group/accordion-group.stories.ts
  src/components/calendar/calendar-renderer/abstract-calendar-renderer.ts
  src/components/calendar/calendar-renderer/base-calendar/__snapshots__/base-calendar.spec.ts.snap
  src/components/calendar/calendar-renderer/base-calendar/base-calendar.html
  src/components/calendar/calendar-renderer/base-calendar/base-calendar.scss
  src/components/calendar/calendar-renderer/base-calendar/base-calendar.spec.ts
  src/components/calendar/calendar-renderer/base-calendar/base-calendar.ts
  src/components/calendar/calendar-state/state/abstract-calendar-state.spec.base.ts
  src/components/calendar/calendar-state/state/abstract-calendar-state.ts
  src/components/calendar/calendar-state/state/calendar-range-date-state.spec.ts
  src/components/calendar/calendar-state/state/calendar-single-date-state.spec.ts
  src/components/calendar/calendar-state/state/calendar-single-date-state.ts
  src/components/calendar/calendar-state/state/calendar-state.ts
  src/components/calendar/calendar.html
  src/components/calendar/calendar.ts
  src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
  src/components/datepicker/datepicker.html
  src/components/datepicker/datepicker.lang.en.json
  src/components/datepicker/datepicker.lang.fr.json
  src/components/datepicker/datepicker.stories.ts
  src/components/datepicker/datepicker.ts
  src/utils/modul-date/modul-date.ts
Labels: breaking change UI, enhancement

#1059 ENA2-6673 - Add abstraction to form and sandbox complex cases
  src/components/form/fallouts/built-in-form-action-fallouts.ts
  src/components/form/form.ts
  src/sandboxes/form/form-complex.sandbox.html
  src/sandboxes/form/form-complex.sandbox.ts
  src/sandboxes/form/form-external-validation.sandbox.ts
  src/utils/form/abstract-control.ts
  src/utils/form/form-array.ts
  src/utils/form/form-control.ts
  src/utils/form/form-group.ts
Labels: enhancement

#1065 different tweaks on the time filter
  src/filters/date/time/__snapshots__/time.stories.ts.snap
  src/filters/date/time/time.lang.en.json
  src/filters/date/time/time.lang.fr.json
  src/filters/date/time/time.stories.ts
  src/filters/date/time/time.ts
Labels: enhancement

#1066 MODUL-1126 - add required-marker prop for the datepicker component
  src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
  src/components/datepicker/datepicker.html
  src/components/datepicker/datepicker.stories.ts
  src/components/form/__snapshots__/form.stories.ts.snap
Labels: bug fix

#1070 Bugfix/timepicker and modal performance
  src/components/timepicker/timepicker.ts
  src/mixins/portal/portal.ts
Labels: bug fix

#1074 MODUL-1135 Ajustements aux messages d'erreur du date et time picker
  src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
  src/components/datepicker/datepicker.lang.en.json
  src/components/datepicker/datepicker.lang.fr.json
  src/components/form/__snapshots__/form.stories.ts.snap
  src/components/timepicker/__snapshots__/timepicker.stories.ts.snap
  src/components/timepicker/timepicker.lang.en.json
  src/components/timepicker/timepicker.lang.fr.json
Labels: enhancement

#1073 MODUL-1132 - Modification du composant input-group
  src/components/form/__snapshots__/form.stories.ts.snap
  src/components/input-group/__snapshots__/input-group.spec.ts.snap
  src/components/input-group/__snapshots__/input-group.stories.ts.snap
  src/components/input-group/input-group.html
  src/components/input-group/input-group.sandbox.html
  src/components/input-group/input-group.sandbox.scss
  src/components/input-group/input-group.sandbox.ts
  src/components/input-group/input-group.scss
  src/components/input-group/input-group.spec.ts
  src/components/input-group/input-group.stories.ts
  src/components/input-group/input-group.ts
  src/components/radio-group/__snapshots__/radio-group.stories.ts.snap
  src/components/radio-group/radio-group.html
  src/components/radio-group/radio-group.scss
  src/components/radio-group/radio-group.stories.ts
  src/components/radio-group/radio-group.ts
Labels: enhancement

#1069 add tooltip to repeater
  src/components/repeater/__snapshots__/repeater.stories.ts.snap
  src/components/repeater/repeater.html
  src/lang/fr.ts
Labels: enhancement

#1081 MODUL-1142 - menu-item used as subitem aren't visible.
  src/components/menu/menu-item/menu-item.html
  src/components/menu/menu-item/menu-item.ts
Labels: bug fix

#1078 MODUL-1138 - Add default htmlaccessor
  src/utils/form/abstract-control.ts
Labels: bug fix

#1086 Bugfix/modul 1145 http query string
  package-lock.json
  package.json
  src/utils/http/http-param-serializer.ts
  src/utils/http/http.spec.ts
  src/utils/http/http.ts
Labels: breaking change

#1079 Feature/modul 1139 m dropdown readonly
  src/components/dropdown/__snapshots__/dropdown.stories.ts.snap
  src/components/dropdown/dropdown.html
  src/components/dropdown/dropdown.scss
  src/components/dropdown/dropdown.stories.ts
  src/components/dropdown/dropdown.ts
  src/mixins/input-management/input-management.ts
Labels: breaking change UI

#1080 Modul-1123 Intégration champ recherche adresse
  src/components/address/address-lookup-field/address-lookup-field.html
  src/components/address/address-lookup-field/address-lookup-field.scss
  src/components/address/address-lookup-field/address-lookup-field.ts
Labels: enhancement

#1090 MODUL-1150 - no margin-top on first element
  src/components/repeater/repeater.scss
  src/components/repeater/repeater.ts
Labels: breaking change UI, enhancement

#1091 Feature/modul 1151 erreur technique case a cocher dans edge
  src/components/checkbox/checkbox.ts
Labels: bug fix

#1089 MODUL-1144 - Fix menu visuals regressions
  src/components/menu/menu-item/menu-item.ts
  src/components/menu/menu.html
  src/components/menu/menu.ts
Labels: bug fix

#1077 Feature/modul 1124 composant avatar
  src/assets/icons/sprites-default.svg
  src/components/avatar/__snapshots__/avatar.stories.ts.snap
  src/components/avatar/avatar.html
  src/components/avatar/avatar.scss
  src/components/avatar/avatar.spec.ts
  src/components/avatar/avatar.stories.ts
  src/components/avatar/avatar.ts
  src/components/component-names.ts
  src/components/components-plugin.ts
Labels: new feature

#1100 Add encoding to value of query string
  src/utils/http/http-param-serializer.ts
  src/utils/http/http.spec.ts
Labels: bug fix

#1094 MODUL-1153 - M-Form not reactive when dynamically adding controls to form groups
  src/utils/form/form-group.ts
Labels: bug fix

#1088 MODUL-1149: Ameliorer slide transition
  src/components/character-count/__snapshots__/character-count.spec.ts.snap
  src/components/character-count/character-count.html
  src/components/menu/menu-item/menu-item.html
  src/components/transitions/accordion-transition/__snapshots__/accordion-transition.stories.ts.snap
  src/components/transitions/accordion-transition/accordion-transition.html
  src/components/transitions/accordion-transition/accordion-transition.stories.ts
  src/components/transitions/accordion-transition/accordion-transition.ts
  src/components/transitions/slide-transition/__snapshots__/slide-transition.stories.ts.snap
  src/components/transitions/slide-transition/slide-transition.html
  src/components/transitions/slide-transition/slide-transition.sandbox.html
  src/components/transitions/slide-transition/slide-transition.scss
  src/components/transitions/slide-transition/slide-transition.stories.ts
  src/components/transitions/slide-transition/slide-transition.ts
  src/components/validation-message/__snapshots__/validation-message.spec.ts.snap
  src/components/validation-message/validation-message.html
Labels: breaking change, bug fix

#1102 MODUL-1161 - change dropdown arrow size
  src/components/address/address-editor/__snapshots__/address-editor.stories.ts.snap
  src/components/dropdown/__snapshots__/dropdown.spec.ts.snap
  src/components/dropdown/__snapshots__/dropdown.stories.ts.snap
  src/components/dropdown/dropdown.html
  src/components/form/__snapshots__/form.stories.ts.snap
Labels: breaking change UI
