Repository ulaval/modul-components, pull requests merged in 2019-08, with the labels that each got.

#1093 MODUL-1152 - Gestion focus avatar
  src/components/avatar/avatar.html
  src/components/avatar/avatar.scss
  src/components/avatar/avatar.spec.ts
  src/components/avatar/avatar.stories.ts
  src/components/avatar/avatar.ts
Labels: breaking change

#1111 BUG FIXE : Change default value of prop disabled - m-accordion-transition
  src/components/transitions/accordion-transition/accordion-transition.ts
Labels: bug fix

#1108 Updated Vue peer dependency to 2.6.4+
  package.json
Labels: breaking change

#1083 Modul-1143 Ajout du composant m-option-title et m-option-separator
  src/components/component-names.ts
  src/components/option/__snapshots__/option.stories.ts.snap
  src/components/option/option-item/option-item-add.ts
  src/components/option/option-item/option-item-archive.ts
  src/components/option/option-item/option-item.html
  src/components/option/option-item/option-item.scss
  src/components/option/option-item/option-item.ts
  src/components/option/option-separator/option-separator.html
  src/components/option/option-separator/option-separator.scss
  src/components/option/option-separator/option-separator.ts
  src/components/option/option-title/option-title.html
  src/components/option/option-title/option-title.scss
  src/components/option/option-title/option-title.ts
  src/components/option/option.html
  src/components/option/option.stories.ts
  src/components/option/option.ts
  src/components/table/__snapshots__/table.stories.ts.snap
Labels: breaking change UI, enhancement

#1109 MODUL-1165: Le texte de la slot par défaut du dialogue est trop gros.
  src/components/dialog/dialog.html
  src/components/dialog/dialog.scss
Labels: enhancement

#1117 MODUL-1171 - selected menu item css
  src/components/menu/menu-item/menu-item.scss
  src/components/menu/menu-item/menu-item.ts
Labels: breaking change

#1119 MODUL-1162 - apply stroke in m-link only with 'svg__chevron'
  src/components/error-pages/error-access-denied/__snapshots__/error-access-denied.stories.ts.snap
  src/components/error-pages/error-browser-not-supported/__snapshots__/error-browser-not-supported.stories.ts.snap
  src/components/error-pages/error-config-not-supported/__snapshots__/error-config-not-supported.stories.ts.snap
  src/components/error-pages/error-cookies-not-supported/__snapshots__/error-cookies-not-supported.stories.ts.snap
  src/components/error-pages/error-page-not-found/__snapshots__/error-page-not-found.stories.ts.snap
  src/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
  src/components/link/__snapshots__/link.stories.ts.snap
  src/components/link/link.html
  src/components/link/link.scss
  src/components/link/link.stories.ts
  src/components/link/link.ts
  src/components/tooltip/__snapshots__/tooltip.spec.ts.snap
Labels: breaking change

#1097 Copy to clipboard input states
  src/components/address/address-editor/__snapshots__/address-editor.stories.ts.snap
  src/components/copy-to-clipboard/__snapshots__/copy-to-clipboard.stories.ts.snap
  src/components/copy-to-clipboard/copy-to-clipboard.html
  src/components/copy-to-clipboard/copy-to-clipboard.stories.ts
  src/components/copy-to-clipboard/copy-to-clipboard.ts
  src/components/form/__snapshots__/form.stories.ts.snap
  src/components/input-group/__snapshots__/input-group.stories.ts.snap
  src/components/textfield/__snapshots__/textfield.stories.ts.snap
  src/components/textfield/textfield.html
  src/mixins/input-state/input-state.ts
Labels: breaking change UI

#1055 MODUL-1122: Améliorer l'affichage du composant m-tree
  src/components/checkbox/checkbox.html
  src/components/checkbox/checkbox.ts
  src/components/tree/__snapshots__/tree.spec.ts.snap
  src/components/tree/tree-icon/tree-icon.html
  src/components/tree/tree-node/__snapshots__/tree-node.spec.ts.snap
  src/components/tree/tree-node/tree-node.html
  src/components/tree/tree-node/tree-node.scss
  src/components/tree/tree-node/tree-node.ts
  src/components/tree/tree.sandbox.html
  src/components/tree/tree.scss
Labels: breaking change UI, enhancement

#1114 Feature/modul 1166 avatar touch
  src/components/avatar/avatar.spec.ts
  src/components/avatar/avatar.stories.ts
  src/components/avatar/avatar.ts
Labels: enhancement

#1123 MODUL-1172 - Modifications font-weight du RTE
  src/components/rich-text-editor/adapter/vue-froala.scss
  src/styles/utils/_typography.scss
  src/styles/variables/_var-font.scss
Labels: breaking change UI

#1126 MODUL-1174 - Add disableUnsort option to m-table column definition AN…
  src/components/table/__snapshots__/table.stories.ts.snap
  src/components/table/table.spec.ts
  src/components/table/table.stories.ts
  src/components/table/table.ts
Labels: breaking change, enhancement

#1084 Address lookup google
  package-lock.json
  package.json
  src/components/address/address-autocomplete-field/address-autocomplete-field.stories.ts
  src/components/address/address-autocomplete-field/address-autocomplete-field.ts
  src/components/address/address-editor/address-editor.stories.ts
  src/components/address/address-editor/address-editor.ts
  src/components/address/address-lookup-field/__snapshots__/address-lookup-field.stories.ts.snap
  src/components/address/address-lookup-field/address-lookup-field.stories.ts
  src/components/address/address-lookup-field/address-lookup-field.ts
  src/components/address/address-reader/__snapshots__/address-reader.stories.ts.snap
  src/components/address/address-reader/address-reader.html
  src/components/address/address-reader/address-reader.ts
  src/components/address/address.ts
  src/typings.d.ts
  src/utils/address-lookup/address-lookup-google-service.ts
  src/utils/address-lookup/address-lookup-google.ts
  src/utils/address-lookup/address-lookup-loqate-service.spec.ts
  src/utils/address-lookup/address-lookup-loqate-service.ts
  src/utils/address-lookup/address-lookup-loqate.ts
  src/utils/address-lookup/address-lookup-response-mapper.ts
  src/utils/address-lookup/address-lookup-service.sandbox.ts
  src/utils/address-lookup/address-lookup-service.ts
  src/utils/address-lookup/address-lookup.plugin.ts
  src/utils/address-lookup/address-lookup.ts
  src/utils/address-lookup/address.ts
  src/utils/address-lookup/google-api.ts
  src/utils/address-lookup/typings-loqate.ts
  tsconfig.json
  tsconfig.lib.json
Labels: new feature

#1120 Loading scheduler
  src/utils/loading-scheduler/__snapshots__/loading-scheduler.stories.ts.snap
  src/utils/loading-scheduler/loading-scheduler.spec.ts
  src/utils/loading-scheduler/loading-scheduler.stories.ts
  src/utils/loading-scheduler/loading-scheduler.ts
  src/utils/loading-scheduler/loading-states.ts
Labels: new feature

#1128 MODUL-1179 - use one level darker for disabled colors
  src/styles/variables/_var-color.scss
Labels: breaking change UI

#1129 Update selected visual indicator (tab underline and tab arrow) when m…
  src/components/navbar/navbar.ts
Labels: bug fix

#1131 MODUL-1181 - régler problème de call de la fonction de validation en …
  src/utils/form/abstract-control.spec.ts
  src/utils/form/abstract-control.ts
Labels: bug fix

#1132 Différencier le errorMessage vs errorMessageDeep
  src/utils/form/abstract-control.ts
Labels: breaking change, enhancement
