Repository ulaval/modul-components, pull requests merged in 2019-06, with the labels that each got.

#948 Feature/modul 946 rte avec titre
  src/assets/icons/svg/Froala-styles.svg
  src/assets/icons/svg/Froala-title.svg
  src/components/rich-text-editor/adapter/submenu-plugin.ts
  src/components/rich-text-editor/adapter/vue-froala.html
  src/components/rich-text-editor/adapter/vue-froala.scss
  src/components/rich-text-editor/adapter/vue-froala.ts
  src/components/rich-text-editor/rich-text-editor-options.ts
  src/components/rich-text-editor/rich-text-editor.lang.en.json
  src/components/rich-text-editor/rich-text-editor.lang.fr.json
  src/components/rich-text-editor/rich-text-editor.sandbox.html
  src/components/rich-text-editor/rich-text-editor.sandbox.scss
  src/components/rich-text-editor/rich-text-editor.sandbox.ts
  src/components/rich-text-editor/rich-text-editor.scss
  src/components/rich-text-editor/rich-text-editor.spec.ts
  src/components/rich-text-editor/rich-text-editor.ts
Labels: enhancement

#1014 MODUL-1083 - changed scrollbar style
  src/components/expandable-layout/__snapshots__/expandable-layout.stories.ts.snap
  src/components/expandable-layout/expandable-layout.scss
  src/components/expandable-layout/expandable-layout.stories.ts
Labels: enhancement

#1017 MODUL-1086 - Changer font-size des titres en mobile
  src/styles/variables/_var-font.scss
Labels: breaking change UI

#930 MODUL-958: Créer un composant de bouton (m-calendar-button) pour le calendrier
  src/components/calendar/calendar-button/calendar-button.html
  src/components/calendar/calendar-button/calendar-button.scss
  src/components/calendar/calendar-button/calendar-button.ts
  src/components/calendar/calendar-renderer/base-calendar/__snapshots__/base-calendar.spec.ts.snap
  src/components/calendar/calendar-renderer/base-calendar/base-calendar.html
  src/components/calendar/calendar-renderer/base-calendar/base-calendar.scss
  src/components/calendar/calendar-renderer/base-calendar/base-calendar.ts
  src/components/calendar/calendar.ts
  src/components/timepicker/timepicker.html
  src/components/timepicker/timepicker.scss
  src/components/timepicker/timepicker.ts
Labels: new feature

#1012 period-picker+ skip internal validation
  src/components/daterangepicker/daterangepicker.html
  src/components/daterangepicker/daterangepicker.sandbox.ts
  src/components/daterangepicker/daterangepicker.spec.ts
  src/components/daterangepicker/daterangepicker.ts
  src/components/periodpicker/periodpicker.html
  src/components/periodpicker/periodpicker.sandbox.ts
  src/components/periodpicker/periodpicker.spec.ts
  src/components/periodpicker/periodpicker.ts
  src/utils/modul-date/modul-date.ts
Labels: enhancement

#1024 MODUL-1090 - Adding sounding names to media queries
  src/mixins/media-queries/media-queries.ts
  src/styles/variables/_var-media-queries.scss
  src/utils/media-queries/media-queries.ts
Labels: enhancement

#1025 MODUL-1091: Supprimer la marge à droite du m-add lorsqu'il n'y a aucun contenu
  src/components/accordion-group/__snapshots__/accordion-group.stories.ts.snap
  src/components/add/__snapshots__/add.stories.ts.snap
  src/components/error-message/__snapshots__/error-message.spec.ts.snap
  src/components/error-pages/error-access-denied/__snapshots__/error-access-denied.stories.ts.snap
  src/components/error-pages/error-browser-not-supported/__snapshots__/error-browser-not-supported.stories.ts.snap
  src/components/error-pages/error-config-not-supported/__snapshots__/error-config-not-supported.stories.ts.snap
  src/components/error-pages/error-cookies-not-supported/__snapshots__/error-cookies-not-supported.stories.ts.snap
  src/components/error-pages/error-page-not-found/__snapshots__/error-page-not-found.stories.ts.snap
  src/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
  src/components/link/__snapshots__/link.stories.ts.snap
  src/components/link/link.html
  src/components/link/link.scss
  src/components/page-not-found/__snapshots__/page-not-found.spec.ts.snap
  src/components/pagination/__snapshots__/pagination.stories.ts.snap
  src/components/repeater/__snapshots__/repeater.stories.ts.snap
  src/components/session-expired/__snapshots__/session-expired.spec.ts.snap
Labels: breaking change UI

#1026 MODUL-1093 - fix unable to reset form control with false-ish initial value
  src/components/tooltip/__snapshots__/tooltip.stories.ts.snap
  src/utils/form/form-control.ts
Labels: bug fix

#1031 Feature/modul 1094 1095 amelioration formulaires
  src/components/form/form.html
  src/components/form/form.lang.en.json
  src/components/form/form.stories.ts
  src/components/form/form.ts
  src/sandboxes/form/form-complex.sandbox.ts
  src/sandboxes/form/form-external-validation.sandbox.html
  src/sandboxes/form/form-external-validation.sandbox.ts
  src/sandboxes/form/form-reactivity.sandbox.html
  src/sandboxes/form/form-reactivity.sandbox.ts
  src/utils/form/abstract-control.ts
  src/utils/form/control-error.ts
  src/utils/form/control-validator-validation-type.ts
  src/utils/form/form-array.ts
  src/utils/form/form-control.ts
  src/utils/form/form-group.spec.ts
  src/utils/form/form-group.ts
  src/utils/form/validation-guard.ts
  src/utils/form/validators/between/between.spec.ts
  src/utils/form/validators/between/between.ts
  src/utils/form/validators/compare/compare.spec.ts
  src/utils/form/validators/compare/compare.ts
  src/utils/form/validators/control-validator.ts
  src/utils/form/validators/date-between/date-between.spec.ts
  src/utils/form/validators/date-between/date-between.ts
  src/utils/form/validators/date-format/date-format.spec.ts
  src/utils/form/validators/date-format/date-format.ts
  src/utils/form/validators/email/email.spec.ts
  src/utils/form/validators/email/email.ts
  src/utils/form/validators/max-length/max-length.spec.ts
  src/utils/form/validators/max-length/max-length.ts
  src/utils/form/validators/max/max.spec.ts
  src/utils/form/validators/max/max.ts
  src/utils/form/validators/min-length/min-length.spec.ts
  src/utils/form/validators/min-length/min-length.ts
  src/utils/form/validators/min/min.spec.ts
  src/utils/form/validators/min/min.ts
  src/utils/form/validators/required/required.spec.ts
  src/utils/form/validators/required/required.ts
  src/utils/str/str.spec.ts
  src/utils/str/str.ts
Labels: breaking change, enhancement

#1006 Feature/modul_1008_searchfield
  src/components/component-names.ts
  src/components/components-plugin.ts
  src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
  src/components/datepicker/datepicker.html
  src/components/decimalfield/__snapshots__/decimalfield.stories.ts.snap
  src/components/decimalfield/decimalfield.html
  src/components/dropdown/__snapshots__/dropdown.spec.ts.snap
  src/components/dropdown/__snapshots__/dropdown.stories.ts.snap
  src/components/dropdown/dropdown.html
  src/components/form/__snapshots__/form.stories.ts.snap
  src/components/input-style/__snapshots__/input-style.spec.ts.snap
  src/components/input-style/__snapshots__/input-style.stories.ts.snap
  src/components/input-style/input-style.html
  src/components/input-style/input-style.scss
  src/components/input-style/input-style.stories.ts
  src/components/input-style/input-style.ts
  src/components/integerfield/__snapshots__/integerfield.spec.ts.snap
  src/components/integerfield/integerfield.html
  src/components/moneyfield/__snapshots__/moneyfield.spec.ts.snap
  src/components/moneyfield/__snapshots__/moneyfield.stories.ts.snap
  src/components/moneyfield/moneyfield.html
  src/components/moneyfield/moneyfield.scss
  src/components/moneyfield/moneyfield.stories.ts
  src/components/periodpicker/__snapshots__/periodpicker.stories.ts.snap
  src/components/rich-text-editor/__snapshots__/rich-text-editor.spec.ts.snap
  src/components/searchfield/__snapshots__/searchfield.stories.ts.snap
  src/components/searchfield/searchfield.html
  src/components/searchfield/searchfield.scss
  src/components/searchfield/searchfield.stories.ts
  src/components/searchfield/searchfield.ts
  src/components/textarea/__snapshots__/textarea.spec.ts.snap
  src/components/textfield/__snapshots__/textfield.stories.ts.snap
  src/components/textfield/textfield.html
  src/components/textfield/textfield.scss
  src/components/textfield/textfield.stories.ts
  src/components/textfield/textfield.ts
  src/components/timepicker/__snapshots__/timepicker.stories.ts.snap
  src/components/timepicker/timepicker.html
  src/components/timepicker/timepicker.stories.ts
  src/styles/functions/_functions.scss
  src/styles/functions/_spacing.scss
  src/styles/mixins/_button.scss
  src/styles/variables/_var-input-style.scss
Labels: breaking change, enhancement, new feature

#1043 Base implementation of time filter + tests
  conf/storybook/utils.ts
  src/components/table/table.stories.ts
  src/filters/date/date-time/date-time.lang.en.json
  src/filters/date/date-time/date-time.spec.ts
  src/filters/date/date.sandbox.html
  src/filters/date/date.sandbox.ts
  src/filters/date/date.ts
  src/filters/date/time/__snapshots__/time.stories.ts.snap
  src/filters/date/time/time.lang.en.json
  src/filters/date/time/time.lang.fr.json
  src/filters/date/time/time.spec.ts
  src/filters/date/time/time.stories.ts
  src/filters/date/time/time.ts
  src/filters/filter-names.ts
  tests/polyfills.js
Labels: new feature

#1044 MODUL-1108 - Problème portal
  src/utils/modul/modul.ts
Labels: bug fix

#1021 MODUL-1067 - Composant m-phonefield
  conf/storybook/addons.ts
  package-lock.json
  package.json
  src/assets/icons/sprites-flags.svg
  src/components/component-names.ts
  src/components/input-mask/input-mask.ts
  src/components/phonefield/__snapshots__/phonefield.stories.ts.snap
  src/components/phonefield/assets/all-countries-en.ts
  src/components/phonefield/assets/all-countries-fr.ts
  src/components/phonefield/phonefield.html
  src/components/phonefield/phonefield.lang.en.json
  src/components/phonefield/phonefield.lang.fr.json
  src/components/phonefield/phonefield.scss
  src/components/phonefield/phonefield.stories.ts
  src/components/phonefield/phonefield.ts
  src/components/select/__snapshots__/select.stories.ts.snap
  src/components/select/select-item/select-item.html
  src/components/select/select-item/select-item.scss
  src/components/select/select-item/select-item.ts
  src/components/select/select.html
  src/components/select/select.lang.en.json
  src/components/select/select.lang.fr.json
  src/components/select/select.scss
  src/components/select/select.stories.ts
  src/components/select/select.ts
  src/lang/en.ts
  src/lang/fr.ts
  src/utils/svg/default-sprites.ts
  tests/storybook/welcome/welcome.html
Labels: new feature

#1027 MODUL-1092 - Ajouter un événement à la fin de l'animation de fermeture des fenêtres (mixin portal)
  src/components/dropdown/dropdown.html
  src/components/dropdown/dropdown.ts
  src/components/file-upload/file-upload.html
  src/components/file-upload/file-upload.ts
  src/components/popper/popper.ts
  src/components/popup/popup.html
  src/components/popup/popup.ts
  src/mixins/portal/portal.ts
Labels: breaking change
