Repository ulaval/modul-components, pull requests merged in 2019-04, with the labels that each got.

#859 Feature/modul 860 sotrybook comp radio
  conf/storybook/sandboxes.storybook.ts
  src/components/radio-group/__snapshots__/radio-group.stories.ts.snap
  src/components/radio-group/radio-group.spec.ts
  src/components/radio-group/radio-group.stories.ts
  src/components/radio/__snapshots__/radio.spec.ts.snap
  src/components/radio/__snapshots__/radio.stories.ts.snap
  src/components/radio/radio.sandbox.html
  src/components/radio/radio.spec.ts
  src/components/radio/radio.stories.ts
Labels: do not review

#860 Feature storybook comp accordeon
  src/components/accordion-group/__snapshots__/accordion-group.stories.ts.snap
  src/components/accordion-group/accordion-group.spec.ts
  src/components/accordion-group/accordion-group.stories.ts
  src/components/accordion/__snapshots__/accordion.stories.ts.snap
  src/components/accordion/accordion.spec.ts
  src/components/accordion/accordion.stories.ts
  src/components/radio-group/radio-group.stories.ts
Labels: do not review

#861 Feature/modul 880 optimize storpybook structure
  src/components/accordion-group/__snapshots__/accordion-group.spec.ts.snap
  src/components/accordion-group/__snapshots__/accordion-group.stories.ts.snap
  src/components/accordion-group/accordion-group.sandbox.html
  src/components/accordion-group/accordion-group.sandbox.ts
  src/components/accordion-group/accordion-group.stories.ts
  src/components/accordion/__snapshots__/accordion.spec.ts.snap
  src/components/accordion/__snapshots__/accordion.stories.ts.snap
  src/components/accordion/accordion.sandbox.html
  src/components/accordion/accordion.sandbox.ts
  src/components/accordion/accordion.stories.ts
  src/components/button/__snapshots__/button.stories.ts.snap
  src/components/button/button.stories.ts
  src/components/checkbox/__snapshots__/checkbox.stories.ts.snap
  src/components/checkbox/checkbox.sandbox.html
  src/components/checkbox/checkbox.sandbox.ts
  src/components/checkbox/checkbox.stories.ts
  src/components/radio-group/__snapshots__/radio-group.spec.ts.snap
  src/components/radio-group/__snapshots__/radio-group.stories.ts.snap
  src/components/radio-group/radio-group.sandbox.html
  src/components/radio-group/radio-group.sandbox.ts
  src/components/radio-group/radio-group.spec.ts
  src/components/radio-group/radio-group.stories.ts
  src/components/radio/__snapshots__/radio.stories.ts.snap
  src/components/radio/radio.sandbox.html
  src/components/radio/radio.sandbox.ts
  src/components/radio/radio.spec.ts
  src/components/radio/radio.stories.ts
Labels: do not review, enhancement

#850 MODUL-858 - Correction filtre dropdown
  src/components/autocomplete/autocomplete.html
  src/components/dropdown/dropdown.ts
Labels: bug fix

#848 MODUL-865 - Autocomplete enhancements
  src/components/autocomplete/autocomplete.html
  src/components/autocomplete/autocomplete.sandbox.html
  src/components/autocomplete/autocomplete.sandbox.ts
  src/components/autocomplete/autocomplete.ts
  src/components/dropdown/dropdown.html
  src/components/dropdown/dropdown.ts
Labels: enhancement

#833 Feature/modul 849 timepicker
  src/components/input-style/input-style.scss
  src/components/timepicker/__snapshots__/timepicker.spec.ts.snap
  src/components/timepicker/__snapshots__/timepicker.stories.ts.snap
  src/components/timepicker/timepicker.html
  src/components/timepicker/timepicker.lang.fr.json
  src/components/timepicker/timepicker.sandbox.html
  src/components/timepicker/timepicker.sandbox.ts
  src/components/timepicker/timepicker.scss
  src/components/timepicker/timepicker.spec.ts
  src/components/timepicker/timepicker.stories.ts
  src/components/timepicker/timepicker.ts
  src/styles/mixins/_scrollbar.scss
Labels: new feature, work in progress

#869 Bugfix/modul 896 sortable not taking no draggable attribut on child element
  src/directives/drag-and-drop/draggable/draggable.ts
  src/directives/sortable/sortable.sandbox.html
  src/directives/sortable/sortable.sandbox.ts
  src/directives/sortable/sortable.ts
Labels: bug fix

#870 MODUL-891 - HttpPluginOptions allows Promise for authorization function
  src/utils/http/http.ts
Labels: enhancement

#880 MODUL-905 - RTE image insertion bugfix
  src/components/rich-text-editor/adapter/vue-froala.ts
  src/components/rich-text-editor/rich-text-editor.sandbox.html
  src/components/rich-text-editor/rich-text-editor.sandbox.ts
Labels: bug fix

#873 MODUL-867 - timezone conversion bugfix
  src/utils/modul-date/modul-date.spec.ts
  src/utils/modul-date/modul-date.ts
Labels: bug fix

#876 fix can't access length of undefined error on textfield
  src/components/textfield/textfield.ts
Labels: bug fix

#879 MODUL-904: Retirer les validateurs de la prop autocomplete du input-management
  src/components/textfield/textfield.html
  src/mixins/input-management/input-management.ts
Labels: bug fix

#866 MODUL-888 - Add slot to accordion-group
  src/components/accordion-group/__snapshots__/accordion-group.stories.ts.snap
  src/components/accordion-group/accordion-group.html
  src/components/accordion-group/accordion-group.scss
  src/components/accordion-group/accordion-group.stories.ts
  src/components/accordion-group/accordion-group.ts
Labels: enhancement

#863 Implémentation de base d'un decimal-field
  package-lock.json
  src/components/component-names.ts
  src/components/decimalfield/__snapshots__/decimal.stories.ts.snap
  src/components/decimalfield/decimal.stories.ts
  src/components/decimalfield/decimalfield.html
  src/components/decimalfield/decimalfield.scss
  src/components/decimalfield/decimalfield.spec.ts
  src/components/decimalfield/decimalfield.ts
  src/components/integerfield/integerfield.ts
  src/components/moneyfield/__snapshots__/moneyfield.spec.ts.snap
  src/components/moneyfield/moneyfield.html
  src/components/moneyfield/moneyfield.ts
  src/utils/l10n/l10n.ts
Labels: new feature

#877 Bugfix/MODUL-863: Retirer le margin-top lorsqu'il n'y a pas de label sur le composant m-input-style
  package-lock.json
  src/components/datepicker/__snapshots__/datepicker.spec.ts.snap
  src/components/decimalfield/__snapshots__/decimal.stories.ts.snap
  src/components/input-style/__snapshots__/input-style.spec.ts.snap
  src/components/input-style/__snapshots__/input-style.stories.ts.snap
  src/components/input-style/input-style.html
  src/components/input-style/input-style.scss
  src/components/input-style/input-style.stories.ts
  src/components/input-style/input-style.ts
  src/components/integerfield/__snapshots__/integerfield.spec.ts.snap
  src/components/moneyfield/__snapshots__/moneyfield.spec.ts.snap
  src/components/rich-text-editor/__snapshots__/rich-text-editor.spec.ts.snap
  src/components/textarea/__snapshots__/textarea.spec.ts.snap
  src/components/textfield/__snapshots__/textfield.spec.ts.snap
  src/components/textfield/textfield.sandbox.html
  src/components/timepicker/__snapshots__/timepicker.stories.ts.snap
Labels: breaking change UI

#895 WIP periodepicker to work with date
  src/components/periodpicker/periodpicker.spec.ts
  src/components/periodpicker/periodpicker.ts
Labels: work in progress

#882 Feature/modul 889 input width
  src/components/datepicker/__snapshots__/datepicker.spec.ts.snap
  src/components/datepicker/datepicker.html
  src/components/datepicker/datepicker.sandbox.html
  src/components/datepicker/datepicker.scss
  src/components/datepicker/datepicker.ts
  src/components/daterangepicker/__snapshots__/daterangepicker.spec.ts.snap
  src/components/daterangepicker/daterangepicker.html
  src/components/daterangepicker/daterangepicker.sandbox.html
  src/components/daterangepicker/daterangepicker.ts
  src/components/decimalfield/__snapshots__/decimal.stories.ts.snap
  src/components/decimalfield/decimalfield.html
  src/components/decimalfield/decimalfield.scss
  src/components/input-style/__snapshots__/input-style.spec.ts.snap
  src/components/input-style/__snapshots__/input-style.stories.ts.snap
  src/components/input-style/input-style.html
  src/components/input-style/input-style.scss
  src/components/input-style/input-style.ts
  src/components/integerfield/__snapshots__/integerfield.spec.ts.snap
  src/components/integerfield/integerfield.scss
  src/components/modal/modal.sandbox.html
  src/components/modal/modal.scss
  src/components/moneyfield/__snapshots__/moneyfield.spec.ts.snap
  src/components/moneyfield/moneyfield.html
  src/components/moneyfield/moneyfield.scss
  src/components/moneyfield/moneyfield.ts
  src/components/periodpicker/__snapshots__/periodpicker.spec.ts.snap
  src/components/periodpicker/periodpicker.html
  src/components/periodpicker/periodpicker.scss
  src/components/periodpicker/periodpicker.ts
  src/components/rich-text-editor/__snapshots__/rich-text-editor.spec.ts.snap
  src/components/textarea/__snapshots__/textarea.spec.ts.snap
  src/components/textfield/__snapshots__/textfield.spec.ts.snap
  src/components/textfield/textfield.sandbox.html
  src/components/textfield/textfield.scss
  src/components/timepicker/__snapshots__/timepicker.stories.ts.snap
  src/mixins/input-width/input-width.ts
  src/styles/mixins/_input.scss
  src/styles/mixins/_mixins.scss
  src/styles/mixins/_typography.scss
Labels: breaking change UI

#890 MODUL-914 - Add centered option to m-table
  src/components/table/__snapshots__/table.stories.ts.snap
  src/components/table/table.html
  src/components/table/table.sandbox.html
  src/components/table/table.sandbox.scss
  src/components/table/table.sandbox.ts
  src/components/table/table.scss
  src/components/table/table.stories.ts
  src/components/table/table.ts
Labels: enhancement

#894 MODUL-919 - Ajout de l'autocomplesion sur autocomplete
  src/components/autocomplete/__snapshots__/autocomplete.spec.ts.snap
  src/components/autocomplete/autocomplete.html
  src/components/autocomplete/autocomplete.ts
  src/components/dropdown/dropdown.html
Labels: enhancement

#896 MODUL-921 - Bogue affichage 'Aucun résultat'
  src/components/autocomplete/autocomplete.ts
Labels: bug fix

#897 MODUL-922 - Changer grosseur icône liste déroulante
  src/components/checkbox/checkbox.html
  src/components/dropdown/__snapshots__/dropdown.spec.ts.snap
  src/components/dropdown/dropdown.html
  src/components/modal/modal.sandbox.html
  src/components/overlay/overlay.sandbox.html
  src/components/periodpicker/periodpicker.sandbox.html
  src/components/radio/radio.html
  src/components/rich-text-editor/rich-text-editor.sandbox.html
  src/components/switch/switch.html
  src/components/validation-message/validation-message.sandbox.html
Labels: breaking change UI

#889 Feature/modul 872 bloq toast delais
  src/components/toast/toast.html
  src/components/toast/toast.spec.ts
  src/components/toast/toast.ts
Labels: bug fix

#891 MODUL-916 - Separated toast service plugin from toast service:
  src/components/form/form.plugin.ts
  src/utils/toast/toast-service.plugin.ts
  src/utils/toast/toast-service.sandbox.ts
  src/utils/toast/toast-service.spec.ts
  src/utils/toast/toast-service.ts
Labels: breaking change

#847 MODUL-864 - Ajout de file-gen-cli pour generer des fichiers dans modul
  README.md
  gencli.json
  package-lock.json
  package.json
  src/meta/cli-templates/component-locale-fr.txt
  src/meta/cli-templates/component-sandbox-template.txt
  src/meta/cli-templates/component-sandbox-vue.txt
  src/meta/cli-templates/component-stories.txt
  src/meta/cli-templates/component-style.txt
  src/meta/cli-templates/component-template.txt
  src/meta/cli-templates/component-test.txt
  src/meta/cli-templates/component-vue.txt
  src/meta/cli-templates/directive-test.txt
  src/meta/cli-templates/directive.txt
  tests/meta/component-generator.js
  tests/meta/component-template.html
  tests/meta/component-template.lang.fr.json
  tests/meta/component-template.sandbox.ts
  tests/meta/component-template.ts
Labels: enhancement

#893 Meilleure gestion du modele dans le timepicker
  src/components/timepicker/__snapshots__/timepicker.stories.ts.snap
  src/components/timepicker/timepicker.html
  src/components/timepicker/timepicker.spec.ts
  src/components/timepicker/timepicker.ts
  src/mixins/input-management/input-management.ts
Labels: enhancement

#902 MODUL-967 - Limit in moneyfield and decimalfield
  src/components/decimalfield/__snapshots__/decimal.stories.ts.snap
  src/components/decimalfield/decimal.stories.ts
  src/components/decimalfield/decimalfield.ts
  src/components/moneyfield/__snapshots__/moneyfield.stories.ts.snap
  src/components/moneyfield/moneyfield.html
  src/components/moneyfield/moneyfield.sandbox.html
  src/components/moneyfield/moneyfield.stories.ts
  src/components/moneyfield/moneyfield.ts
  src/components/textfield/textfield.sandbox.html
Labels: enhancement

#884 MODUL-577 - Nouveau component Add
  src/components/add/__snapshots__/add.stories.ts.snap
  src/components/add/add.html
  src/components/add/add.sandbox.html
  src/components/add/add.sandbox.ts
  src/components/add/add.scss
  src/components/add/add.stories.ts
  src/components/add/add.ts
  src/components/checkbox/checkbox.stories.ts
  src/components/component-names.ts
  src/components/components-plugin.ts
  src/components/link/link.ts
Labels: new feature

#878 MODUL-902 - removed sorted column
  src/components/table/__snapshots__/table.spec.ts.snap
  src/components/table/table.html
  src/components/table/table.spec.ts
  src/components/table/table.stories.ts
  src/components/table/table.ts
Labels: breaking change, enhancement

#901 MODUL-925 - Prevent adding images into RTE without using m-file-upload
  src/components/rich-text-editor/adapter/vue-froala.ts
  src/components/rich-text-editor/rich-text-editor.sandbox.html
Labels: bug fix

#888 Modul 804/saisie manuelle de la date
  .vscode/launch.json
  src/components/datepicker/__snapshots__/datepicker.spec.ts.snap
  src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
  src/components/datepicker/datepicker.html
  src/components/datepicker/datepicker.lang.en.json
  src/components/datepicker/datepicker.lang.fr.json
  src/components/datepicker/datepicker.sandbox.html
  src/components/datepicker/datepicker.sandbox.ts
  src/components/datepicker/datepicker.spec.ts
  src/components/datepicker/datepicker.stories.ts
  src/components/datepicker/datepicker.ts
  src/components/input-mask/__snapshots__/input-mask.stories.ts.snap
  src/components/input-mask/input-mask.sandbox.html
  src/components/input-mask/input-mask.sandbox.ts
  src/components/input-mask/input-mask.stories.ts
  src/components/input-mask/input-mask.ts
  src/components/periodpicker/periodpicker.spec.ts
  src/components/periodpicker/periodpicker.ts
  src/mixins/input-management/input-management.ts
  src/utils/modul-date/modul-date.ts
Labels: breaking change, enhancement

#909 fixed typing problem in cleave.js
  src/components/input-mask/input-mask.ts
Labels: bug fix

#916 MODUL-940 - Fix gestion de la saisie manuelle dans le periodpicker
  src/components/periodpicker/__snapshots__/periodpicker.spec.ts.snap
  src/components/periodpicker/__snapshots__/periodpicker.stories.ts.snap
  src/components/periodpicker/periodpicker.spec.ts
  src/components/periodpicker/periodpicker.stories.ts
  src/components/periodpicker/periodpicker.ts
Labels: bug fix

#923 MODUL-947 - centered property on column table
  src/components/table/table.ts
Labels: bug fix

#900 Add the m-link component to storybook
  src/components/link/__snapshots__/link.spec.ts.snap
  src/components/link/__snapshots__/link.stories.ts.snap
  src/components/link/link.sandbox.html
  src/components/link/link.sandbox.ts
  src/components/link/link.spec.ts
  src/components/link/link.stories.ts
Labels: enhancement

#899 Add the m-menu/menu-item component to storybook
  src/components/menu/__snapshots__/menu.spec.ts.snap
  src/components/menu/__snapshots__/menu.stories.ts.snap
  src/components/menu/menu.sandbox.html
  src/components/menu/menu.sandbox.ts
  src/components/menu/menu.spec.ts
  src/components/menu/menu.stories.ts
Labels: enhancement

#913 Add the m-icon component to storybook
  src/components/icon/__snapshots__/icon.spec.ts.snap
  src/components/icon/__snapshots__/icon.stories.ts.snap
  src/components/icon/icon.sandbox.html
  src/components/icon/icon.sandbox.ts
  src/components/icon/icon.spec.ts
  src/components/icon/icon.stories.ts
Labels: enhancement

#924 Datepicker - Added Prop for to hide internal error and close popup on tab
  src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
  src/components/datepicker/datepicker.spec.ts
  src/components/datepicker/datepicker.stories.ts
  src/components/datepicker/datepicker.ts
  src/components/daterangepicker/daterangepicker.html
  src/components/daterangepicker/daterangepicker.ts
Labels: enhancement

#922 timepicker popup model update
  src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
  src/components/decimalfield/__snapshots__/decimal.stories.ts.snap
  src/components/input-style/__snapshots__/input-style.stories.ts.snap
  src/components/input-style/input-style.ts
  src/components/integerfield/__snapshots__/integerfield.spec.ts.snap
  src/components/moneyfield/__snapshots__/moneyfield.spec.ts.snap
  src/components/periodpicker/__snapshots__/periodpicker.stories.ts.snap
  src/components/rich-text-editor/__snapshots__/rich-text-editor.spec.ts.snap
  src/components/textarea/__snapshots__/textarea.spec.ts.snap
  src/components/textfield/__snapshots__/textfield.spec.ts.snap
  src/components/timepicker/__snapshots__/timepicker.stories.ts.snap
  src/components/timepicker/timepicker.html
  src/components/timepicker/timepicker.stories.ts
  src/components/timepicker/timepicker.ts
Labels: work in progress

#938 MODUL-953 - Add stories for error-page-technical-difficulty
  src/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
  src/components/error-pages/error-technical-difficulty/error-technical-difficulty.stories.ts
Labels: enhancement

#937 Add the Error Page component (Page not found) in storybook
  src/components/error-pages/error-page-not-found/__snapshots__/error-page-not-found.stories.ts.snap
  src/components/error-pages/error-page-not-found/error-page-not-found.stories.ts
  src/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
  src/components/error-pages/error-technical-difficulty/error-technical-difficulty.stories.ts
Labels: enhancement

#936 Add the Error Page component (Cookies not supported) in storybook
  src/components/error-pages/error-cookies-not-supported/__snapshots__/error-cookies-not-supported.stories.ts.snap
  src/components/error-pages/error-cookies-not-supported/error-cookies-not-supported.stories.ts
  src/components/error-pages/error-page-not-found/__snapshots__/error-page-not-found.stories.ts.snap
  src/components/error-pages/error-page-not-found/error-page-not-found.stories.ts
  src/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
  src/components/error-pages/error-technical-difficulty/error-technical-difficulty.stories.ts
Labels: enhancement

#935 Add the Error Page component (Config not supported) in storybook
  src/components/error-pages/error-config-not-supported/__snapshots__/error-config-not-supported.stories.ts.snap
  src/components/error-pages/error-config-not-supported/error-config-not-supported.stories.ts
  src/components/error-pages/error-cookies-not-supported/__snapshots__/error-cookies-not-supported.stories.ts.snap
  src/components/error-pages/error-cookies-not-supported/error-cookies-not-supported.stories.ts
  src/components/error-pages/error-page-not-found/__snapshots__/error-page-not-found.stories.ts.snap
  src/components/error-pages/error-page-not-found/error-page-not-found.stories.ts
  src/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
  src/components/error-pages/error-technical-difficulty/error-technical-difficulty.stories.ts
Labels: enhancement

#934 Add the Error Page component (browser not supported) in storybook.
  package-lock.json
  package.json
  src/components/datepicker/__snapshots__/datepicker.stories.ts.snap
  src/components/datepicker/datepicker.spec.ts
  src/components/datepicker/datepicker.stories.ts
  src/components/datepicker/datepicker.ts
  src/components/daterangepicker/daterangepicker.html
  src/components/daterangepicker/daterangepicker.ts
  src/components/decimalfield/__snapshots__/decimal.stories.ts.snap
  src/components/error-pages/error-browser-not-supported/__snapshots__/error-browser-not-supported.stories.ts.snap
  src/components/error-pages/error-browser-not-supported/error-browser-not-supported.stories.ts
  src/components/error-pages/error-config-not-supported/__snapshots__/error-config-not-supported.stories.ts.snap
  src/components/error-pages/error-config-not-supported/error-config-not-supported.stories.ts
  src/components/error-pages/error-cookies-not-supported/__snapshots__/error-cookies-not-supported.stories.ts.snap
  src/components/error-pages/error-cookies-not-supported/error-cookies-not-supported.stories.ts
  src/components/error-pages/error-page-not-found/__snapshots__/error-page-not-found.stories.ts.snap
  src/components/error-pages/error-page-not-found/error-page-not-found.stories.ts
  src/components/error-pages/error-technical-difficulty/__snapshots__/error-technical-difficulty.stories.ts.snap
  src/components/error-pages/error-technical-difficulty/error-technical-difficulty.stories.ts
  src/components/input-style/__snapshots__/input-style.stories.ts.snap
  src/components/input-style/input-style.ts
  src/components/integerfield/__snapshots__/integerfield.spec.ts.snap
  src/components/link/link.ts
  src/components/moneyfield/__snapshots__/moneyfield.spec.ts.snap
  src/components/periodpicker/__snapshots__/periodpicker.stories.ts.snap
  src/components/rich-text-editor/__snapshots__/rich-text-editor.spec.ts.snap
  src/components/textarea/__snapshots__/textarea.spec.ts.snap
  src/components/textfield/__snapshots__/textfield.spec.ts.snap
  src/components/timepicker/__snapshots__/timepicker.stories.ts.snap
  src/components/timepicker/timepicker.html
  src/components/timepicker/timepicker.stories.ts
  src/components/timepicker/timepicker.ts
Labels: enhancement
