Repository ulaval/modul-components, pull requests merged in 2019-03, with the labels that each got.

#736 Feature/modul 728 calendar
  src/components/calendar/__snapshots__/calendar.spec.ts.snap
  src/components/calendar/calendar-renderer/__snapshots__/simple-calendar.spec.ts.snap
  src/components/calendar/calendar-renderer/base-calendar/__snapshots__/base-calendar.spec.ts.snap
  src/components/calendar/calendar-renderer/base-calendar/base-calendar.html
  src/components/calendar/calendar-renderer/base-calendar/base-calendar.scss
  src/components/calendar/calendar-renderer/base-calendar/base-calendar.spec.ts
  src/components/calendar/calendar-renderer/base-calendar/base-calendar.ts
  src/components/calendar/calendar-renderer/simple-calendar.html
  src/components/calendar/calendar-renderer/simple-calendar.scss
  src/components/calendar/calendar-state/state/abstract-calendar-state.ts
  src/components/calendar/calendar-state/state/calendar-range-date-state.spec.ts
  src/components/calendar/calendar-state/state/calendar-range-date-state.ts
  src/components/calendar/calendar-state/state/calendar-single-date-state.spec.ts
  src/components/calendar/calendar-state/state/calendar-single-date-state.ts
  src/components/calendar/calendar-state/state/calendar-state.ts
  src/components/calendar/calendar.html
  src/components/calendar/calendar.sandbox.html
  src/components/calendar/calendar.scss
  src/components/calendar/calendar.ts
Labels: enhancement

#756 Feature/modul 629 slide transition
  src/components/component-names.ts
  src/components/components-plugin.ts
  src/components/slide-transition/slide-transition.html
  src/components/slide-transition/slide-transition.sandbox.html
  src/components/slide-transition/slide-transition.sandbox.ts
  src/components/slide-transition/slide-transition.scss
  src/components/slide-transition/slide-transition.ts
Labels: new feature

#774 MODUL-791 - moved images styles into common mixin
  src/components/rich-text-editor/adapter/vue-froala.scss
  src/styles/mixins/_froala.scss
Labels: bug fix

#785 Extract of component MIntergerfield from MTextfield
  conf/webpack.config.js
  src/components/component-names.ts
  src/components/input-style/input-style.scss
  src/components/integerfield/__snapshots__/integerfield.spec.ts.snap
  src/components/integerfield/integerfield.html
  src/components/integerfield/integerfield.sandbox.html
  src/components/integerfield/integerfield.sandbox.ts
  src/components/integerfield/integerfield.scss
  src/components/integerfield/integerfield.spec.ts
  src/components/integerfield/integerfield.ts
  src/components/textfield/textfield.html
  src/components/textfield/textfield.sandbox.html
  src/components/textfield/textfield.ts
  tests/app/navigation/navigation.ts
  tsconfig.json
Labels: breaking change, new feature

#786 Modul 794 mise en place sous composante input mask
  package-lock.json
  package.json
  src/components/input-mask/input-mask.html
  src/components/input-mask/input-mask.sandbox.html
  src/components/input-mask/input-mask.sandbox.ts
  src/components/input-mask/input-mask.ts
Labels: enhancement

#777 MODUL-795 - resoudre probleme de focus dans texte riche
  src/components/rich-text-editor/adapter/vue-froala.scss
  src/components/rich-text-editor/adapter/vue-froala.ts
Labels: bug fix

#782 MODUL-796 - m-table - Ajout du tri sur les colonnes
  package-lock.json
  src/components/calendar/__snapshots__/calendar.spec.ts.snap
  src/components/icon-button/__snapshots__/icon-button.spec.ts.snap
  src/components/icon-button/icon-button.html
  src/components/icon-button/icon-button.scss
  src/components/icon-button/icon-button.ts
  src/components/table/__snapshots__/table.spec.ts.snap
  src/components/table/table.html
  src/components/table/table.sandbox.html
  src/components/table/table.sandbox.ts
  src/components/table/table.scss
  src/components/table/table.spec.ts
  src/components/table/table.ts
Labels: enhancement

#784 MODUL-803 - Correction z-index text riche editor
  src/components/input-style/input-style.scss
  src/components/rich-text-editor/adapter/vue-froala.scss
  src/components/rich-text-editor/rich-text-editor.sandbox.html
  src/components/rich-text-editor/rich-text-editor.scss
Labels: bug fix

#800 MODUL-819 - m-rich-text-editor : cursor behaviour fix
  src/styles/mixins/_froala.scss
Labels: bug fix

#799 MODUL-817 - Ajouter et retirer des champs au formulaire après sa création
  src/components/form/form.sandbox.html
  src/components/form/form.sandbox.ts
  src/utils/form/form.spec.ts
  src/utils/form/form.ts
Labels: enhancement

#808 MODUL-825 - Seulement considérer les erreurs des champs dans le message du toast du formulaire
  src/components/form/form.ts
Labels: bug fix

#798 MODUL-776 - Fix 1er, remove full mode, add cases in sandbox
  src/filters/date/date.sandbox.html
  src/filters/date/date.sandbox.ts
  src/filters/date/date/date.ts
  src/filters/date/period/period.spec.ts
  src/filters/date/period/period.ts
Labels: breaking change, bug fix

#796 Fix daterangepicker labels initialization
  src/components/daterangepicker/daterangepicker.ts
Labels: bug fix

#803 MODUL-818 - Change background-color of parent and color checkbox on r…
  src/components/checkbox/checkbox.scss
  src/components/tree/tree-node/tree-node.scss
Labels: bug fix

#804 periodpicker: Update model on blur only
  src/components/periodpicker/periodpicker.spec.ts
  src/components/periodpicker/periodpicker.ts
Labels: enhancement

#806 MODUL-822 - Update Froala version to 2.9.3
  package-lock.json
  package.json
Labels: bug fix

#807 Bugfix/integerfield maxlength number representation
  src/components/integerfield/__snapshots__/integerfield.spec.ts.snap
  src/components/integerfield/integerfield.sandbox.html
  src/components/integerfield/integerfield.ts
Labels: bug fix

#816 MODUL-831: Ajouter le mode "definition" au tooltip
  src/components/datepicker/__snapshots__/datepicker.spec.ts.snap
  src/components/icon-button/__snapshots__/icon-button.spec.ts.snap
  src/components/icon-button/icon-button.html
  src/components/list-item/__snapshots__/list-item.spec.ts.snap
  src/components/message/__snapshots__/message.spec.ts.snap
  src/components/pagination/__snapshots__/pagination.spec.ts.snap
  src/components/timepicker/__snapshots__/timepicker.spec.ts.snap
  src/components/tooltip/__snapshots__/tooltip.spec.ts.snap
  src/components/tooltip/tooltip.html
  src/components/tooltip/tooltip.sandbox.html
  src/components/tooltip/tooltip.sandbox.ts
  src/components/tooltip/tooltip.scss
  src/components/tooltip/tooltip.ts
Labels: breaking change, enhancement

#819 Feature/modul 828 allow dialog type presets
  src/components/dialog/dialog.html
  src/components/dialog/dialog.lang.en.json
  src/components/dialog/dialog.sandbox.html
  src/components/dialog/dialog.scss
  src/components/dialog/dialog.ts
Labels: enhancement

#817 Create money filter
  src/components/calendar/calendar.ts
  src/filters/filter-names.ts
  src/filters/filters-plugin.ts
  src/filters/money/money.sandbox.html
  src/filters/money/money.sandbox.ts
  src/filters/money/money.spec.ts
  src/filters/money/money.ts
  src/utils/enums/enums.ts
Labels: new feature

#820 Feature/modul 829 add hint to dialog
  src/assets/icons/sprites-default.svg
  src/components/dialog/dialog.html
  src/components/dialog/dialog.sandbox.html
  src/components/dialog/dialog.scss
  src/components/dialog/dialog.ts
  src/styles/variables/_var-color.scss
Labels: enhancement

#821 add money-field
  src/components/component-names.ts
  src/components/integerfield/integerfield.sandbox.html
  src/components/integerfield/integerfield.sandbox.ts
  src/components/integerfield/integerfield.ts
  src/components/moneyfield/__snapshots__/moneyfield.spec.ts.snap
  src/components/moneyfield/moneyfield.html
  src/components/moneyfield/moneyfield.sandbox.html
  src/components/moneyfield/moneyfield.sandbox.ts
  src/components/moneyfield/moneyfield.spec.ts
  src/components/moneyfield/moneyfield.ts
  src/utils/i18n/i18n.ts
  src/utils/l10n/l10n.ts
  src/utils/money/money.ts
  src/utils/utils-plugin.ts
Labels: new feature

#822 m-radio and m-radio-group - read-only prop
  src/components/radio-group/radio-group.sandbox.html
  src/components/radio-group/radio-group.ts
  src/components/radio/radio.html
  src/components/radio/radio.sandbox.html
  src/components/radio/radio.ts
Labels: breaking change

#825 Feature/modul 838 input state readonly
  src/components/datepicker/datepicker.html
  src/components/datepicker/datepicker.sandbox.html
  src/components/input-group/__snapshots__/input-group.spec.ts.snap
  src/components/input-style/input-style.html
  src/components/input-style/input-style.scss
  src/components/integerfield/integerfield.html
  src/components/integerfield/integerfield.sandbox.html
  src/components/textarea/textarea.html
  src/components/textarea/textarea.sandbox.html
  src/components/textfield/textfield.html
  src/components/timepicker/timepicker.html
  src/components/timepicker/timepicker.sandbox.html
  src/components/timepicker/timepicker.sandbox.ts
  src/mixins/input-state/input-state.ts
Labels: enhancement

#824 Modul 830/storybook
  conf/storybook/addons.ts
  conf/storybook/all.storybook.ts
  conf/storybook/config.jest.ts
  conf/storybook/config.ts
  conf/storybook/manager-head.html
  conf/storybook/modul.ts
  conf/storybook/modulTheme.js
  conf/storybook/preview-head.html
  conf/storybook/sandbox-loader.ts
  conf/storybook/sandboxes.storybook.ts
  conf/storybook/storyshots.test.ts
  conf/storybook/utils.ts
  conf/storybook/webpack.config.js
  conf/webpack.base.js
  conf/webpack.config.js
  jest.config.js
  package-lock.json
  package.json
  src/components/button/__snapshots__/button.spec.ts.snap
  src/components/button/__snapshots__/button.stories.ts.snap
  src/components/button/button.sandbox.html
  src/components/button/button.sandbox.ts
  src/components/button/button.spec.ts
  src/components/button/button.stories.ts
  tests/setup.ts
Labels: enhancement

#823 Feature/modul 833 allow btn link combos in dialog
  src/components/dialog/dialog.html
  src/components/dialog/dialog.sandbox.html
  src/components/dialog/dialog.scss
  src/components/dialog/dialog.ts
Labels: enhancement

#805 MODUL-810 - Calendrier : reste à faire suite la première livraison du…
  src/components/calendar/__snapshots__/calendar.spec.ts.snap
  src/components/calendar/calendar-renderer/abstract-calendar-renderer.ts
  src/components/calendar/calendar-renderer/base-calendar/__snapshots__/base-calendar.spec.ts.snap
  src/components/calendar/calendar-renderer/base-calendar/base-calendar.html
  src/components/calendar/calendar-renderer/base-calendar/base-calendar.scss
  src/components/calendar/calendar-renderer/base-calendar/base-calendar.ts
  src/components/calendar/calendar-state/state/abstract-calendar-state.ts
  src/components/calendar/calendar-state/state/calendar-range-date-state.spec.ts
  src/components/calendar/calendar-state/state/calendar-range-date-state.ts
  src/components/calendar/calendar-state/state/calendar-single-date-state.spec.ts
  src/components/calendar/calendar-state/state/calendar-state.ts
  src/components/calendar/calendar.sandbox.html
  src/styles/variables/_var-color.scss
Labels: enhancement

#834 MODUL-851: Ajuster la largeur des icones dans les composants modul
  src/components/datepicker/__snapshots__/datepicker.spec.ts.snap
  src/components/error-message/__snapshots__/error-message.spec.ts.snap
  src/components/menu/menu-item/menu-item.html
  src/components/message/__snapshots__/message.spec.ts.snap
  src/components/message/message.html
  src/components/message/message.scss
  src/components/page-not-found/__snapshots__/page-not-found.spec.ts.snap
  src/components/session-expired/__snapshots__/session-expired.spec.ts.snap
  src/components/timepicker/__snapshots__/timepicker.spec.ts.snap
  src/components/toast/toast.html
  src/components/validation-message/__snapshots__/validation-message.spec.ts.snap
  src/components/validation-message/validation-message.html
Labels: bug fix

#843 MODUL-857 - Remettre la propriété touched au formulaire
  src/components/form/form-field.spec.ts
  src/components/form/form-field.ts
  src/utils/form/form-field/form-field.ts
Labels: enhancement

#842 MODUL-839 $dialog service
  src/components/dialog/dialog.sandbox.html
  src/components/dialog/dialog.sandbox.ts
  src/components/dialog/dialog.ts
  src/utils/dialog/alert.ts
  src/utils/dialog/confirm.ts
  src/utils/dialog/dialog-service.sandbox.html
  src/utils/dialog/dialog-service.sandbox.ts
  src/utils/dialog/dialog-service.ts
Labels: breaking change, enhancement

#832 Feature/modul 183 delete dots on label title
  src/components/accordion-group/__snapshots__/accordion-group.spec.ts.snap
  src/components/accordion/__snapshots__/accordion.spec.ts.snap
  src/components/accordion/accordion.html
  src/components/accordion/accordion.lang.en.json
  src/components/accordion/accordion.lang.fr.json
  src/components/accordion/accordion.ts
  src/components/error-message/__snapshots__/error-message.spec.ts.snap
  src/components/menu/__snapshots__/menu.spec.ts.snap
  src/components/menu/menu.html
  src/components/menu/menu.ts
  src/components/plus/plus.html
  src/components/plus/plus.ts
  src/components/scroll-top/__snapshots__/scroll-top.spec.ts.snap
  src/components/scroll-top/scroll-top.html
  src/components/scroll-top/scroll-top.lang.en.json
  src/components/scroll-top/scroll-top.lang.fr.json
  src/lang/en.ts
  src/lang/fr.ts
Labels: enhancement

#844 Feature/modul 855 overflow on slide transition
  src/components/slide-transition/slide-transition.sandbox.html
  src/components/slide-transition/slide-transition.sandbox.ts
  src/components/slide-transition/slide-transition.scss
  src/components/slide-transition/slide-transition.ts
Labels: bug fix

#835 MODUL-852: Optimiser le balisage du composant m-validation-message
  src/components/checkbox/__snapshots__/checkbox.stories.ts.snap
  src/components/datepicker/__snapshots__/datepicker.spec.ts.snap
  src/components/file-select/__snapshots__/file-select.spec.ts.snap
  src/components/integerfield/__snapshots__/integerfield.spec.ts.snap
  src/components/moneyfield/__snapshots__/moneyfield.spec.ts.snap
  src/components/radio-group/__snapshots__/radio-group.spec.ts.snap
  src/components/rich-text-editor/__snapshots__/rich-text-editor.spec.ts.snap
  src/components/textarea/__snapshots__/textarea.spec.ts.snap
  src/components/textfield/__snapshots__/textfield.spec.ts.snap
  src/components/timepicker/__snapshots__/timepicker.spec.ts.snap
  src/components/validation-message/__snapshots__/validation-message.spec.ts.snap
  src/components/validation-message/validation-message.html
  src/components/validation-message/validation-message.sandbox.html
  src/components/validation-message/validation-message.sandbox.ts
  src/components/validation-message/validation-message.scss
  src/components/validation-message/validation-message.spec.ts
  src/components/validation-message/validation-message.ts
Labels: enhancement
