Repository ulaval/modul-components, pull requests merged in 2019-01, with the labels that each got.

#632 Feature/modul 628 git hooks
  conf/hooks/commit-msg.js
  conf/hooks/hook-utils.js
  conf/hooks/prepare-msg.js
  package-lock.json
  package.json
Labels: enhancement

#613 Feature/toast manager
  src/components/toast/toast.sandbox.html
  src/components/toast/toast.scss
  src/components/toast/toast.spec.ts
  src/components/toast/toast.ts
  src/mixins/portal/portal.ts
  src/utils/toast/toast-service.sandbox.html
  src/utils/toast/toast-service.sandbox.ts
  src/utils/toast/toast-service.spec.ts
  src/utils/toast/toast-service.ts
  src/utils/utils-names.ts
  src/utils/utils-plugin.ts
  src/utils/vue/vue.ts
Labels: breaking change, new feature

#623 Feature/modul 611 component calendar
  src/components/calendar/__snapshots__/calendar.spec.ts.snap
  src/components/calendar/calendar-renderer/__snapshots__/simple-calendar.spec.ts.snap
  src/components/calendar/calendar-renderer/abstract-calendar-renderer.ts
  src/components/calendar/calendar-renderer/simple-calendar.html
  src/components/calendar/calendar-renderer/simple-calendar.scss
  src/components/calendar/calendar-renderer/simple-calendar.spec.ts
  src/components/calendar/calendar-renderer/simple-calendar.ts
  src/components/calendar/calendar-state/__snapshots__/calendar-state-machine.spec.ts.snap
  src/components/calendar/calendar-state/calendar-state-machine.spec.ts
  src/components/calendar/calendar-state/calendar-state-machine.ts
  src/components/calendar/calendar-state/state/abstract-calendar-state.spec.base.ts
  src/components/calendar/calendar-state/state/abstract-calendar-state.ts
  src/components/calendar/calendar-state/state/calendar-range-date-state.spec.ts
  src/components/calendar/calendar-state/state/calendar-range-date-state.ts
  src/components/calendar/calendar-state/state/calendar-single-date-state.spec.ts
  src/components/calendar/calendar-state/state/calendar-single-date-state.ts
  src/components/calendar/calendar-state/state/calendar-state.ts
  src/components/calendar/calendar.html
  src/components/calendar/calendar.lang.en.json
  src/components/calendar/calendar.lang.fr.json
  src/components/calendar/calendar.sandbox.html
  src/components/calendar/calendar.sandbox.ts
  src/components/calendar/calendar.spec.ts
  src/components/calendar/calendar.ts
  src/components/component-names.ts
  src/components/components-plugin.ts
  src/components/datepicker/datepicker.html
  src/components/datepicker/datepicker.sandbox.html
  src/components/datepicker/datepicker.sandbox.ts
  src/components/datepicker/datepicker.ts
  src/components/dropdown/dropdown.ts
  src/components/login/__snapshots__/login.spec.ts.snap
  src/components/periodpicker/periodpicker.html
  src/components/periodpicker/periodpicker.sandbox.html
  src/components/periodpicker/periodpicker.sandbox.ts
  src/components/periodpicker/periodpicker.ts
  src/components/textfield/__snapshots__/textfield.spec.ts.snap
  src/components/textfield/textfield.html
  src/components/textfield/textfield.ts
  src/components/timepicker/__snapshots__/timepicker.spec.ts.snap
  src/lang/fr.ts
  src/mixins/input-management/input-management.ts
  src/mixins/input-popup/input-popup.ts
  src/utils/logger/logger.ts
  src/utils/modul-date/modul-date.spec.ts
  src/utils/modul-date/modul-date.ts
Labels: enhancement, new feature

#628 MODUL-352 - input style & dropdown cursor
  src/components/dropdown/__snapshots__/dropdown.spec.ts.snap
  src/components/dropdown/dropdown.html
  src/components/dropdown/dropdown.scss
  src/components/dropdown/dropdown.ts
  src/components/input-style/__snapshots__/input-style.spec.ts.snap
  src/components/input-style/input-style.html
  src/components/input-style/input-style.scss
  src/components/input-style/input-style.spec.ts
  src/components/input-style/input-style.ts
  src/components/textfield/textfield.sandbox.html
  src/mixins/input-state/input-state.ts
Labels: bug fix

#629 Feature/ena2 max height on dropdown
  src/components/dropdown-item/dropdown-item.scss
  src/components/dropdown/dropdown.sandbox.html
Labels: bug fix

#639 MODUL-643 - Un champ de saisie avec la prop valid="true" devrait être vert
  src/components/input-style/input-style.scss
  src/components/textfield/textfield.sandbox.html
Labels: bug fix

#642 MODUL-645 - Ajouter les emit focus et blur sur le m-radio
  src/components/button-group/button-group.ts
  src/components/radio-group/radio-group.html
  src/components/radio-group/radio-group.sandbox.html
  src/components/radio-group/radio-group.sandbox.ts
  src/components/radio-group/radio-group.ts
  src/components/radio/radio.sandbox.html
  src/components/radio/radio.sandbox.ts
  src/components/radio/radio.ts
Labels: bug fix

#647 Bump froala version to 2.9.1 and fix a regression caused by it
  package-lock.json
  package.json
  src/components/rich-text-editor/rich-text-editor-options.ts
Labels: bug fix

#645 MODUL-582 - Fixed parent auto-select multinode, added a test
  src/components/tree/tree-node/tree-node.spec.ts
  src/components/tree/tree-node/tree-node.ts
Labels: bug fix

#655 MODUL-659 new icon email-send
  src/assets/icons/sprites-default.svg
Labels: enhancement

#659 addSprites returns the div ID, so it can be used with any sprite
  src/utils/svg/sprites.ts
Labels: enhancement

#640 MODUL-644 juster l'espacement entre les champs de saisie et leur message d'erreur
  src/components/datepicker/__snapshots__/datepicker.spec.ts.snap
  src/components/datepicker/datepicker.html
  src/components/datepicker/datepicker.scss
  src/components/dropdown/__snapshots__/dropdown.spec.ts.snap
  src/components/dropdown/dropdown.html
  src/components/dropdown/dropdown.sandbox.html
  src/components/dropdown/dropdown.scss
  src/components/rich-text-editor/__snapshots__/rich-text-editor.spec.ts.snap
  src/components/rich-text-editor/rich-text-editor.html
  src/components/rich-text-editor/rich-text-editor.scss
  src/components/textarea/textarea.html
  src/components/textarea/textarea.scss
  src/components/textfield/textfield.html
  src/components/textfield/textfield.scss
  src/components/timepicker/__snapshots__/timepicker.spec.ts.snap
  src/components/timepicker/timepicker.html
  src/components/timepicker/timepicker.scss
  src/components/validation-message/validation-message.html
  src/components/validation-message/validation-message.scss
  src/mixins/input-state/input-state.ts
Labels: bug fix

#672 MODUL-677 - fix IE11 font issue
  src/styles/base/_base.scss
Labels: bug fix

#667 MODUL-665 - M-Table - word-break: break-word
  src/components/table/table.sandbox.html
  src/components/table/table.sandbox.ts
  src/components/table/table.scss
Labels: bug fix

#669 MODUL-671 - added monochrome skin
  src/components/progress/__snapshots__/progress.spec.ts.snap
  src/components/progress/progress.html
  src/components/progress/progress.sandbox.html
  src/components/progress/progress.scss
  src/components/progress/progress.spec.ts
  src/components/progress/progress.ts
Labels: enhancement

#678 Bugfix/modul 678 fix special chars
  src/utils/i18n/i18n-service.sandbox.html
  src/utils/i18n/i18n-service.sandbox.lang.fr.json
  src/utils/i18n/i18n-service.sandbox.scss
  src/utils/i18n/i18n-service.sandbox.ts
  src/utils/i18n/i18n.spec.ts
  src/utils/i18n/i18n.ts
Labels: bug fix

#679 MODUL-692: Le emit('open') et le emit('close') sont appelées à deux reprises sur les composant utilisant m-popup
  src/components/datepicker/datepicker.html
  src/components/datepicker/datepicker.spec.ts
  src/components/datepicker/datepicker.ts
  src/components/dropdown/dropdown.html
  src/components/dropdown/dropdown.sandbox.html
  src/components/dropdown/dropdown.sandbox.ts
  src/components/dropdown/dropdown.ts
  src/components/input-style/input-style.scss
  src/components/popper/popper.sandbox.html
  src/components/popper/popper.sandbox.ts
  src/components/popup/popup.html
  src/components/popup/popup.sandbox.html
  src/components/popup/popup.sandbox.ts
  src/components/popup/popup.ts
Labels: bug fix

#685 MODUL-697 - Add input type number
  src/components/input-style/input-style.scss
  src/components/textfield/textfield.sandbox.html
  src/components/textfield/textfield.spec.ts
  src/components/textfield/textfield.ts
Labels: enhancement

#688 MODUL-703 - Force disabled color in rich-text-editor
  src/components/rich-text-editor/adapter/vue-froala.scss
Labels: bug fix
